package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PymeFacncDetProv generated by hbm2java
 */
public class PymeFacncDetProv implements java.io.Serializable {

	private long facprovdId;
	private PymeProductos pymeProductos;
	private PymeFacncEncProv pymeFacncEncProv;
	private Long facprovdCantidad;
	private String facprovdDetalle;
	private BigDecimal facprovdTotalLineaLocal;
	private String facprovdTotalLineaExt;
	private String facprovdCreadoPor;
	private Date facprovdCreadoEl;

	public PymeFacncDetProv() {
	}

	public PymeFacncDetProv(long facprovdId, PymeFacncEncProv pymeFacncEncProv) {
		this.facprovdId = facprovdId;
		this.pymeFacncEncProv = pymeFacncEncProv;
	}

	public PymeFacncDetProv(long facprovdId, PymeProductos pymeProductos, PymeFacncEncProv pymeFacncEncProv,
			Long facprovdCantidad, String facprovdDetalle, BigDecimal facprovdTotalLineaLocal,
			String facprovdTotalLineaExt, String facprovdCreadoPor, Date facprovdCreadoEl) {
		this.facprovdId = facprovdId;
		this.pymeProductos = pymeProductos;
		this.pymeFacncEncProv = pymeFacncEncProv;
		this.facprovdCantidad = facprovdCantidad;
		this.facprovdDetalle = facprovdDetalle;
		this.facprovdTotalLineaLocal = facprovdTotalLineaLocal;
		this.facprovdTotalLineaExt = facprovdTotalLineaExt;
		this.facprovdCreadoPor = facprovdCreadoPor;
		this.facprovdCreadoEl = facprovdCreadoEl;
	}

	public long getFacprovdId() {
		return this.facprovdId;
	}

	public void setFacprovdId(long facprovdId) {
		this.facprovdId = facprovdId;
	}

	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	public PymeFacncEncProv getPymeFacncEncProv() {
		return this.pymeFacncEncProv;
	}

	public void setPymeFacncEncProv(PymeFacncEncProv pymeFacncEncProv) {
		this.pymeFacncEncProv = pymeFacncEncProv;
	}

	public Long getFacprovdCantidad() {
		return this.facprovdCantidad;
	}

	public void setFacprovdCantidad(Long facprovdCantidad) {
		this.facprovdCantidad = facprovdCantidad;
	}

	public String getFacprovdDetalle() {
		return this.facprovdDetalle;
	}

	public void setFacprovdDetalle(String facprovdDetalle) {
		this.facprovdDetalle = facprovdDetalle;
	}

	public BigDecimal getFacprovdTotalLineaLocal() {
		return this.facprovdTotalLineaLocal;
	}

	public void setFacprovdTotalLineaLocal(BigDecimal facprovdTotalLineaLocal) {
		this.facprovdTotalLineaLocal = facprovdTotalLineaLocal;
	}

	public String getFacprovdTotalLineaExt() {
		return this.facprovdTotalLineaExt;
	}

	public void setFacprovdTotalLineaExt(String facprovdTotalLineaExt) {
		this.facprovdTotalLineaExt = facprovdTotalLineaExt;
	}

	public String getFacprovdCreadoPor() {
		return this.facprovdCreadoPor;
	}

	public void setFacprovdCreadoPor(String facprovdCreadoPor) {
		this.facprovdCreadoPor = facprovdCreadoPor;
	}

	public Date getFacprovdCreadoEl() {
		return this.facprovdCreadoEl;
	}

	public void setFacprovdCreadoEl(Date facprovdCreadoEl) {
		this.facprovdCreadoEl = facprovdCreadoEl;
	}

}
