package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeProductos generated by hbm2java
 */
public class PymeProductos implements java.io.Serializable {

	private long producId;
	private PymeDtipos pymeDtiposByProducMedida;
	private PymeDtipos pymeDtiposByProducEstado;
	private PymeMlistaPrecios pymeMlistaPrecios;
	private PymeDtipos pymeDtiposByProducTipo;
	private String producIdAlterno;
	private String producDescripcion;
	private long etaId;
	private BigDecimal producPeso;
	private long producExistencia;
	private Long producReservado;
	private Long producDisponible;
	private Date producCreadoEl;
	private String producCreadoPor;
	private Set<PymeDentradas> pymeDentradases = new HashSet<PymeDentradas>(0);
	private Set<PymeFacncDetProv> pymeFacncDetProvs = new HashSet<PymeFacncDetProv>(0);
	private Set<PymeDsalidas> pymeDsalidases = new HashSet<PymeDsalidas>(0);
	private Set<PymeFacncDetCli> pymeFacncDetClis = new HashSet<PymeFacncDetCli>(0);
	private Set<PymeNdDetCli> pymeNdDetClis = new HashSet<PymeNdDetCli>(0);
	private Set<PymeNdDetProv> pymeNdDetProvs = new HashSet<PymeNdDetProv>(0);

	public PymeProductos() {
	}

	public PymeProductos(long producId, PymeDtipos pymeDtiposByProducEstado, PymeMlistaPrecios pymeMlistaPrecios,
			String producIdAlterno, String producDescripcion, long etaId, long producExistencia) {
		this.producId = producId;
		this.pymeDtiposByProducEstado = pymeDtiposByProducEstado;
		this.pymeMlistaPrecios = pymeMlistaPrecios;
		this.producIdAlterno = producIdAlterno;
		this.producDescripcion = producDescripcion;
		this.etaId = etaId;
		this.producExistencia = producExistencia;
	}

	public PymeProductos(long producId, PymeDtipos pymeDtiposByProducMedida, PymeDtipos pymeDtiposByProducEstado,
			PymeMlistaPrecios pymeMlistaPrecios, PymeDtipos pymeDtiposByProducTipo, String producIdAlterno,
			String producDescripcion, long etaId, BigDecimal producPeso, long producExistencia, Long producReservado,
			Long producDisponible, Date producCreadoEl, String producCreadoPor, Set<PymeDentradas> pymeDentradases,
			Set<PymeFacncDetProv> pymeFacncDetProvs, Set<PymeDsalidas> pymeDsalidases,
			Set<PymeFacncDetCli> pymeFacncDetClis, Set<PymeNdDetCli> pymeNdDetClis, Set<PymeNdDetProv> pymeNdDetProvs) {
		this.producId = producId;
		this.pymeDtiposByProducMedida = pymeDtiposByProducMedida;
		this.pymeDtiposByProducEstado = pymeDtiposByProducEstado;
		this.pymeMlistaPrecios = pymeMlistaPrecios;
		this.pymeDtiposByProducTipo = pymeDtiposByProducTipo;
		this.producIdAlterno = producIdAlterno;
		this.producDescripcion = producDescripcion;
		this.etaId = etaId;
		this.producPeso = producPeso;
		this.producExistencia = producExistencia;
		this.producReservado = producReservado;
		this.producDisponible = producDisponible;
		this.producCreadoEl = producCreadoEl;
		this.producCreadoPor = producCreadoPor;
		this.pymeDentradases = pymeDentradases;
		this.pymeFacncDetProvs = pymeFacncDetProvs;
		this.pymeDsalidases = pymeDsalidases;
		this.pymeFacncDetClis = pymeFacncDetClis;
		this.pymeNdDetClis = pymeNdDetClis;
		this.pymeNdDetProvs = pymeNdDetProvs;
	}

	public long getProducId() {
		return this.producId;
	}

	public void setProducId(long producId) {
		this.producId = producId;
	}

	public PymeDtipos getPymeDtiposByProducMedida() {
		return this.pymeDtiposByProducMedida;
	}

	public void setPymeDtiposByProducMedida(PymeDtipos pymeDtiposByProducMedida) {
		this.pymeDtiposByProducMedida = pymeDtiposByProducMedida;
	}

	public PymeDtipos getPymeDtiposByProducEstado() {
		return this.pymeDtiposByProducEstado;
	}

	public void setPymeDtiposByProducEstado(PymeDtipos pymeDtiposByProducEstado) {
		this.pymeDtiposByProducEstado = pymeDtiposByProducEstado;
	}

	public PymeMlistaPrecios getPymeMlistaPrecios() {
		return this.pymeMlistaPrecios;
	}

	public void setPymeMlistaPrecios(PymeMlistaPrecios pymeMlistaPrecios) {
		this.pymeMlistaPrecios = pymeMlistaPrecios;
	}

	public PymeDtipos getPymeDtiposByProducTipo() {
		return this.pymeDtiposByProducTipo;
	}

	public void setPymeDtiposByProducTipo(PymeDtipos pymeDtiposByProducTipo) {
		this.pymeDtiposByProducTipo = pymeDtiposByProducTipo;
	}

	public String getProducIdAlterno() {
		return this.producIdAlterno;
	}

	public void setProducIdAlterno(String producIdAlterno) {
		this.producIdAlterno = producIdAlterno;
	}

	public String getProducDescripcion() {
		return this.producDescripcion;
	}

	public void setProducDescripcion(String producDescripcion) {
		this.producDescripcion = producDescripcion;
	}

	public long getEtaId() {
		return this.etaId;
	}

	public void setEtaId(long etaId) {
		this.etaId = etaId;
	}

	public BigDecimal getProducPeso() {
		return this.producPeso;
	}

	public void setProducPeso(BigDecimal producPeso) {
		this.producPeso = producPeso;
	}

	public long getProducExistencia() {
		return this.producExistencia;
	}

	public void setProducExistencia(long producExistencia) {
		this.producExistencia = producExistencia;
	}

	public Long getProducReservado() {
		return this.producReservado;
	}

	public void setProducReservado(Long producReservado) {
		this.producReservado = producReservado;
	}

	public Long getProducDisponible() {
		return this.producDisponible;
	}

	public void setProducDisponible(Long producDisponible) {
		this.producDisponible = producDisponible;
	}

	public Date getProducCreadoEl() {
		return this.producCreadoEl;
	}

	public void setProducCreadoEl(Date producCreadoEl) {
		this.producCreadoEl = producCreadoEl;
	}

	public String getProducCreadoPor() {
		return this.producCreadoPor;
	}

	public void setProducCreadoPor(String producCreadoPor) {
		this.producCreadoPor = producCreadoPor;
	}

	public Set<PymeDentradas> getPymeDentradases() {
		return this.pymeDentradases;
	}

	public void setPymeDentradases(Set<PymeDentradas> pymeDentradases) {
		this.pymeDentradases = pymeDentradases;
	}

	public Set<PymeFacncDetProv> getPymeFacncDetProvs() {
		return this.pymeFacncDetProvs;
	}

	public void setPymeFacncDetProvs(Set<PymeFacncDetProv> pymeFacncDetProvs) {
		this.pymeFacncDetProvs = pymeFacncDetProvs;
	}

	public Set<PymeDsalidas> getPymeDsalidases() {
		return this.pymeDsalidases;
	}

	public void setPymeDsalidases(Set<PymeDsalidas> pymeDsalidases) {
		this.pymeDsalidases = pymeDsalidases;
	}

	public Set<PymeFacncDetCli> getPymeFacncDetClis() {
		return this.pymeFacncDetClis;
	}

	public void setPymeFacncDetClis(Set<PymeFacncDetCli> pymeFacncDetClis) {
		this.pymeFacncDetClis = pymeFacncDetClis;
	}

	public Set<PymeNdDetCli> getPymeNdDetClis() {
		return this.pymeNdDetClis;
	}

	public void setPymeNdDetClis(Set<PymeNdDetCli> pymeNdDetClis) {
		this.pymeNdDetClis = pymeNdDetClis;
	}

	public Set<PymeNdDetProv> getPymeNdDetProvs() {
		return this.pymeNdDetProvs;
	}

	public void setPymeNdDetProvs(Set<PymeNdDetProv> pymeNdDetProvs) {
		this.pymeNdDetProvs = pymeNdDetProvs;
	}

}
