package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PymeTipoCambio generated by hbm2java
 */
public class PymeTipoCambio implements java.io.Serializable {

	private long tcId;
	private BigDecimal tcCompra;
	private String tcMoneda;
	private Date tcFecha;

	public PymeTipoCambio() {
	}

	public PymeTipoCambio(long tcId, BigDecimal tcCompra, Date tcFecha) {
		this.tcId = tcId;
		this.tcCompra = tcCompra;
		this.tcFecha = tcFecha;
	}

	public PymeTipoCambio(long tcId, BigDecimal tcCompra, String tcMoneda, Date tcFecha) {
		this.tcId = tcId;
		this.tcCompra = tcCompra;
		this.tcMoneda = tcMoneda;
		this.tcFecha = tcFecha;
	}

	public long getTcId() {
		return this.tcId;
	}

	public void setTcId(long tcId) {
		this.tcId = tcId;
	}

	public BigDecimal getTcCompra() {
		return this.tcCompra;
	}

	public void setTcCompra(BigDecimal tcCompra) {
		this.tcCompra = tcCompra;
	}

	public String getTcMoneda() {
		return this.tcMoneda;
	}

	public void setTcMoneda(String tcMoneda) {
		this.tcMoneda = tcMoneda;
	}

	public Date getTcFecha() {
		return this.tcFecha;
	}

	public void setTcFecha(Date tcFecha) {
		this.tcFecha = tcFecha;
	}

}
