package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * PymeSysPermisos generated by hbm2java
 */
public class PymeSysPermisos implements java.io.Serializable {

	private long sysPerId;
	private String sysPerCod;
	private String sysPerDesc;
	private String sysPerCreadoPor;
	private Date sysPerCreadoEl;
	private PymeSysSeguridad pymeSysSeguridad;

	public PymeSysPermisos() {
	}

	public PymeSysPermisos(long sysPerId, String sysPerCod, String sysPerDesc) {
		this.sysPerId = sysPerId;
		this.sysPerCod = sysPerCod;
		this.sysPerDesc = sysPerDesc;
	}

	public PymeSysPermisos(long sysPerId, String sysPerCod, String sysPerDesc, String sysPerCreadoPor,
			Date sysPerCreadoEl, PymeSysSeguridad pymeSysSeguridad) {
		this.sysPerId = sysPerId;
		this.sysPerCod = sysPerCod;
		this.sysPerDesc = sysPerDesc;
		this.sysPerCreadoPor = sysPerCreadoPor;
		this.sysPerCreadoEl = sysPerCreadoEl;
		this.pymeSysSeguridad = pymeSysSeguridad;
	}

	public long getSysPerId() {
		return this.sysPerId;
	}

	public void setSysPerId(long sysPerId) {
		this.sysPerId = sysPerId;
	}

	public String getSysPerCod() {
		return this.sysPerCod;
	}

	public void setSysPerCod(String sysPerCod) {
		this.sysPerCod = sysPerCod;
	}

	public String getSysPerDesc() {
		return this.sysPerDesc;
	}

	public void setSysPerDesc(String sysPerDesc) {
		this.sysPerDesc = sysPerDesc;
	}

	public String getSysPerCreadoPor() {
		return this.sysPerCreadoPor;
	}

	public void setSysPerCreadoPor(String sysPerCreadoPor) {
		this.sysPerCreadoPor = sysPerCreadoPor;
	}

	public Date getSysPerCreadoEl() {
		return this.sysPerCreadoEl;
	}

	public void setSysPerCreadoEl(Date sysPerCreadoEl) {
		this.sysPerCreadoEl = sysPerCreadoEl;
	}

	public PymeSysSeguridad getPymeSysSeguridad() {
		return this.pymeSysSeguridad;
	}

	public void setPymeSysSeguridad(PymeSysSeguridad pymeSysSeguridad) {
		this.pymeSysSeguridad = pymeSysSeguridad;
	}

}
