package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeNdEncProv generated by hbm2java
 */
public class PymeNdEncProv implements java.io.Serializable {

	private long ndprovId;
	private PymeDtipos pymeDtiposByNdprovEstado;
	private PymeDtipos pymeDtiposByNdprovTipoFacnd;
	private long ndprovConsectivo;
	private BigDecimal idSoc;
	private String ndprovSocNombre;
	private BigDecimal ndprovTotalLocal;
	private BigDecimal ndprovTotalExtranjero;
	private String ndprovTipoCambio;
	private Date ndprovFechaDoc;
	private Date ndprovContabilizacion;
	private Long ndprovDocBase;
	private Long ndprovDocDestino;
	private String ndprovComentarios;
	private BigDecimal proyId;
	private Set<PymeNdDetProv> pymeNdDetProvs = new HashSet<PymeNdDetProv>(0);

	public PymeNdEncProv() {
	}

	public PymeNdEncProv(long ndprovId, PymeDtipos pymeDtiposByNdprovEstado, PymeDtipos pymeDtiposByNdprovTipoFacnd,
			long ndprovConsectivo, BigDecimal proyId) {
		this.ndprovId = ndprovId;
		this.pymeDtiposByNdprovEstado = pymeDtiposByNdprovEstado;
		this.pymeDtiposByNdprovTipoFacnd = pymeDtiposByNdprovTipoFacnd;
		this.ndprovConsectivo = ndprovConsectivo;
		this.proyId = proyId;
	}

	public PymeNdEncProv(long ndprovId, PymeDtipos pymeDtiposByNdprovEstado, PymeDtipos pymeDtiposByNdprovTipoFacnd,
			long ndprovConsectivo, BigDecimal idSoc, String ndprovSocNombre, BigDecimal ndprovTotalLocal,
			BigDecimal ndprovTotalExtranjero, String ndprovTipoCambio, Date ndprovFechaDoc, Date ndprovContabilizacion,
			Long ndprovDocBase, Long ndprovDocDestino, String ndprovComentarios, BigDecimal proyId,
			Set<PymeNdDetProv> pymeNdDetProvs) {
		this.ndprovId = ndprovId;
		this.pymeDtiposByNdprovEstado = pymeDtiposByNdprovEstado;
		this.pymeDtiposByNdprovTipoFacnd = pymeDtiposByNdprovTipoFacnd;
		this.ndprovConsectivo = ndprovConsectivo;
		this.idSoc = idSoc;
		this.ndprovSocNombre = ndprovSocNombre;
		this.ndprovTotalLocal = ndprovTotalLocal;
		this.ndprovTotalExtranjero = ndprovTotalExtranjero;
		this.ndprovTipoCambio = ndprovTipoCambio;
		this.ndprovFechaDoc = ndprovFechaDoc;
		this.ndprovContabilizacion = ndprovContabilizacion;
		this.ndprovDocBase = ndprovDocBase;
		this.ndprovDocDestino = ndprovDocDestino;
		this.ndprovComentarios = ndprovComentarios;
		this.proyId = proyId;
		this.pymeNdDetProvs = pymeNdDetProvs;
	}

	public long getNdprovId() {
		return this.ndprovId;
	}

	public void setNdprovId(long ndprovId) {
		this.ndprovId = ndprovId;
	}

	public PymeDtipos getPymeDtiposByNdprovEstado() {
		return this.pymeDtiposByNdprovEstado;
	}

	public void setPymeDtiposByNdprovEstado(PymeDtipos pymeDtiposByNdprovEstado) {
		this.pymeDtiposByNdprovEstado = pymeDtiposByNdprovEstado;
	}

	public PymeDtipos getPymeDtiposByNdprovTipoFacnd() {
		return this.pymeDtiposByNdprovTipoFacnd;
	}

	public void setPymeDtiposByNdprovTipoFacnd(PymeDtipos pymeDtiposByNdprovTipoFacnd) {
		this.pymeDtiposByNdprovTipoFacnd = pymeDtiposByNdprovTipoFacnd;
	}

	public long getNdprovConsectivo() {
		return this.ndprovConsectivo;
	}

	public void setNdprovConsectivo(long ndprovConsectivo) {
		this.ndprovConsectivo = ndprovConsectivo;
	}

	public BigDecimal getIdSoc() {
		return this.idSoc;
	}

	public void setIdSoc(BigDecimal idSoc) {
		this.idSoc = idSoc;
	}

	public String getNdprovSocNombre() {
		return this.ndprovSocNombre;
	}

	public void setNdprovSocNombre(String ndprovSocNombre) {
		this.ndprovSocNombre = ndprovSocNombre;
	}

	public BigDecimal getNdprovTotalLocal() {
		return this.ndprovTotalLocal;
	}

	public void setNdprovTotalLocal(BigDecimal ndprovTotalLocal) {
		this.ndprovTotalLocal = ndprovTotalLocal;
	}

	public BigDecimal getNdprovTotalExtranjero() {
		return this.ndprovTotalExtranjero;
	}

	public void setNdprovTotalExtranjero(BigDecimal ndprovTotalExtranjero) {
		this.ndprovTotalExtranjero = ndprovTotalExtranjero;
	}

	public String getNdprovTipoCambio() {
		return this.ndprovTipoCambio;
	}

	public void setNdprovTipoCambio(String ndprovTipoCambio) {
		this.ndprovTipoCambio = ndprovTipoCambio;
	}

	public Date getNdprovFechaDoc() {
		return this.ndprovFechaDoc;
	}

	public void setNdprovFechaDoc(Date ndprovFechaDoc) {
		this.ndprovFechaDoc = ndprovFechaDoc;
	}

	public Date getNdprovContabilizacion() {
		return this.ndprovContabilizacion;
	}

	public void setNdprovContabilizacion(Date ndprovContabilizacion) {
		this.ndprovContabilizacion = ndprovContabilizacion;
	}

	public Long getNdprovDocBase() {
		return this.ndprovDocBase;
	}

	public void setNdprovDocBase(Long ndprovDocBase) {
		this.ndprovDocBase = ndprovDocBase;
	}

	public Long getNdprovDocDestino() {
		return this.ndprovDocDestino;
	}

	public void setNdprovDocDestino(Long ndprovDocDestino) {
		this.ndprovDocDestino = ndprovDocDestino;
	}

	public String getNdprovComentarios() {
		return this.ndprovComentarios;
	}

	public void setNdprovComentarios(String ndprovComentarios) {
		this.ndprovComentarios = ndprovComentarios;
	}

	public BigDecimal getProyId() {
		return this.proyId;
	}

	public void setProyId(BigDecimal proyId) {
		this.proyId = proyId;
	}

	public Set<PymeNdDetProv> getPymeNdDetProvs() {
		return this.pymeNdDetProvs;
	}

	public void setPymeNdDetProvs(Set<PymeNdDetProv> pymeNdDetProvs) {
		this.pymeNdDetProvs = pymeNdDetProvs;
	}

}
