package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeNdEncCli generated by hbm2java
 */
public class PymeNdEncCli implements java.io.Serializable {

	private long ndcliId;
	private PymeDtipos pymeDtiposByNdcliEstado;
	private PymeDtipos pymeDtiposByNdcliTipoFacnd;
	private long ndcliConsectivo;
	private BigDecimal idSoc;
	private String ndcliSocNombre;
	private BigDecimal ndcliTotalLocal;
	private BigDecimal ndcliTotalExtranjero;
	private String ndcliTipoCambio;
	private Date ndcliFechaDoc;
	private Date ndcliContabilizacion;
	private Long ndcliDocBase;
	private Long ndcliDocDestino;
	private String ndcliComentarios;
	private BigDecimal proyId;
	private Set<PymeNdDetCli> pymeNdDetClis = new HashSet<PymeNdDetCli>(0);

	public PymeNdEncCli() {
	}

	public PymeNdEncCli(long ndcliId, PymeDtipos pymeDtiposByNdcliEstado, PymeDtipos pymeDtiposByNdcliTipoFacnd,
			long ndcliConsectivo, BigDecimal proyId) {
		this.ndcliId = ndcliId;
		this.pymeDtiposByNdcliEstado = pymeDtiposByNdcliEstado;
		this.pymeDtiposByNdcliTipoFacnd = pymeDtiposByNdcliTipoFacnd;
		this.ndcliConsectivo = ndcliConsectivo;
		this.proyId = proyId;
	}

	public PymeNdEncCli(long ndcliId, PymeDtipos pymeDtiposByNdcliEstado, PymeDtipos pymeDtiposByNdcliTipoFacnd,
			long ndcliConsectivo, BigDecimal idSoc, String ndcliSocNombre, BigDecimal ndcliTotalLocal,
			BigDecimal ndcliTotalExtranjero, String ndcliTipoCambio, Date ndcliFechaDoc, Date ndcliContabilizacion,
			Long ndcliDocBase, Long ndcliDocDestino, String ndcliComentarios, BigDecimal proyId,
			Set<PymeNdDetCli> pymeNdDetClis) {
		this.ndcliId = ndcliId;
		this.pymeDtiposByNdcliEstado = pymeDtiposByNdcliEstado;
		this.pymeDtiposByNdcliTipoFacnd = pymeDtiposByNdcliTipoFacnd;
		this.ndcliConsectivo = ndcliConsectivo;
		this.idSoc = idSoc;
		this.ndcliSocNombre = ndcliSocNombre;
		this.ndcliTotalLocal = ndcliTotalLocal;
		this.ndcliTotalExtranjero = ndcliTotalExtranjero;
		this.ndcliTipoCambio = ndcliTipoCambio;
		this.ndcliFechaDoc = ndcliFechaDoc;
		this.ndcliContabilizacion = ndcliContabilizacion;
		this.ndcliDocBase = ndcliDocBase;
		this.ndcliDocDestino = ndcliDocDestino;
		this.ndcliComentarios = ndcliComentarios;
		this.proyId = proyId;
		this.pymeNdDetClis = pymeNdDetClis;
	}

	public long getNdcliId() {
		return this.ndcliId;
	}

	public void setNdcliId(long ndcliId) {
		this.ndcliId = ndcliId;
	}

	public PymeDtipos getPymeDtiposByNdcliEstado() {
		return this.pymeDtiposByNdcliEstado;
	}

	public void setPymeDtiposByNdcliEstado(PymeDtipos pymeDtiposByNdcliEstado) {
		this.pymeDtiposByNdcliEstado = pymeDtiposByNdcliEstado;
	}

	public PymeDtipos getPymeDtiposByNdcliTipoFacnd() {
		return this.pymeDtiposByNdcliTipoFacnd;
	}

	public void setPymeDtiposByNdcliTipoFacnd(PymeDtipos pymeDtiposByNdcliTipoFacnd) {
		this.pymeDtiposByNdcliTipoFacnd = pymeDtiposByNdcliTipoFacnd;
	}

	public long getNdcliConsectivo() {
		return this.ndcliConsectivo;
	}

	public void setNdcliConsectivo(long ndcliConsectivo) {
		this.ndcliConsectivo = ndcliConsectivo;
	}

	public BigDecimal getIdSoc() {
		return this.idSoc;
	}

	public void setIdSoc(BigDecimal idSoc) {
		this.idSoc = idSoc;
	}

	public String getNdcliSocNombre() {
		return this.ndcliSocNombre;
	}

	public void setNdcliSocNombre(String ndcliSocNombre) {
		this.ndcliSocNombre = ndcliSocNombre;
	}

	public BigDecimal getNdcliTotalLocal() {
		return this.ndcliTotalLocal;
	}

	public void setNdcliTotalLocal(BigDecimal ndcliTotalLocal) {
		this.ndcliTotalLocal = ndcliTotalLocal;
	}

	public BigDecimal getNdcliTotalExtranjero() {
		return this.ndcliTotalExtranjero;
	}

	public void setNdcliTotalExtranjero(BigDecimal ndcliTotalExtranjero) {
		this.ndcliTotalExtranjero = ndcliTotalExtranjero;
	}

	public String getNdcliTipoCambio() {
		return this.ndcliTipoCambio;
	}

	public void setNdcliTipoCambio(String ndcliTipoCambio) {
		this.ndcliTipoCambio = ndcliTipoCambio;
	}

	public Date getNdcliFechaDoc() {
		return this.ndcliFechaDoc;
	}

	public void setNdcliFechaDoc(Date ndcliFechaDoc) {
		this.ndcliFechaDoc = ndcliFechaDoc;
	}

	public Date getNdcliContabilizacion() {
		return this.ndcliContabilizacion;
	}

	public void setNdcliContabilizacion(Date ndcliContabilizacion) {
		this.ndcliContabilizacion = ndcliContabilizacion;
	}

	public Long getNdcliDocBase() {
		return this.ndcliDocBase;
	}

	public void setNdcliDocBase(Long ndcliDocBase) {
		this.ndcliDocBase = ndcliDocBase;
	}

	public Long getNdcliDocDestino() {
		return this.ndcliDocDestino;
	}

	public void setNdcliDocDestino(Long ndcliDocDestino) {
		this.ndcliDocDestino = ndcliDocDestino;
	}

	public String getNdcliComentarios() {
		return this.ndcliComentarios;
	}

	public void setNdcliComentarios(String ndcliComentarios) {
		this.ndcliComentarios = ndcliComentarios;
	}

	public BigDecimal getProyId() {
		return this.proyId;
	}

	public void setProyId(BigDecimal proyId) {
		this.proyId = proyId;
	}

	public Set<PymeNdDetCli> getPymeNdDetClis() {
		return this.pymeNdDetClis;
	}

	public void setPymeNdDetClis(Set<PymeNdDetCli> pymeNdDetClis) {
		this.pymeNdDetClis = pymeNdDetClis;
	}

}
