package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeFacncEncCli generated by hbm2java
 */
public class PymeFacncEncCli implements java.io.Serializable {

	private long facId;
	private PymeDtipos pymeDtiposByFacEstado;
	private PymeProyecto pymeProyecto;
	private PymeDtipos pymeDtiposByFacTipoFacnd;
	private PymeDtipos pymeDtiposByFacTipoDoc;
	private long facConsectivo;
	private BigDecimal idSoc;
	private String facSocNombre;
	private BigDecimal facTotalLocal;
	private BigDecimal facTotalExtranjero;
	private String facTipoCambio;
	private Date facFechaDoc;
	private Date facContabilizacion;
	private Long facDocBase;
	private Long facDocDestino;
	private String facComentarios;
	private Set<PymeFacncDetCli> pymeFacncDetClis = new HashSet<PymeFacncDetCli>(0);

	public PymeFacncEncCli() {
	}

	public PymeFacncEncCli(long facId, PymeDtipos pymeDtiposByFacEstado, PymeProyecto pymeProyecto,
			PymeDtipos pymeDtiposByFacTipoFacnd, PymeDtipos pymeDtiposByFacTipoDoc, long facConsectivo) {
		this.facId = facId;
		this.pymeDtiposByFacEstado = pymeDtiposByFacEstado;
		this.pymeProyecto = pymeProyecto;
		this.pymeDtiposByFacTipoFacnd = pymeDtiposByFacTipoFacnd;
		this.pymeDtiposByFacTipoDoc = pymeDtiposByFacTipoDoc;
		this.facConsectivo = facConsectivo;
	}

	public PymeFacncEncCli(long facId, PymeDtipos pymeDtiposByFacEstado, PymeProyecto pymeProyecto,
			PymeDtipos pymeDtiposByFacTipoFacnd, PymeDtipos pymeDtiposByFacTipoDoc, long facConsectivo,
			BigDecimal idSoc, String facSocNombre, BigDecimal facTotalLocal, BigDecimal facTotalExtranjero,
			String facTipoCambio, Date facFechaDoc, Date facContabilizacion, Long facDocBase, Long facDocDestino,
			String facComentarios, Set<PymeFacncDetCli> pymeFacncDetClis) {
		this.facId = facId;
		this.pymeDtiposByFacEstado = pymeDtiposByFacEstado;
		this.pymeProyecto = pymeProyecto;
		this.pymeDtiposByFacTipoFacnd = pymeDtiposByFacTipoFacnd;
		this.pymeDtiposByFacTipoDoc = pymeDtiposByFacTipoDoc;
		this.facConsectivo = facConsectivo;
		this.idSoc = idSoc;
		this.facSocNombre = facSocNombre;
		this.facTotalLocal = facTotalLocal;
		this.facTotalExtranjero = facTotalExtranjero;
		this.facTipoCambio = facTipoCambio;
		this.facFechaDoc = facFechaDoc;
		this.facContabilizacion = facContabilizacion;
		this.facDocBase = facDocBase;
		this.facDocDestino = facDocDestino;
		this.facComentarios = facComentarios;
		this.pymeFacncDetClis = pymeFacncDetClis;
	}

	public long getFacId() {
		return this.facId;
	}

	public void setFacId(long facId) {
		this.facId = facId;
	}

	public PymeDtipos getPymeDtiposByFacEstado() {
		return this.pymeDtiposByFacEstado;
	}

	public void setPymeDtiposByFacEstado(PymeDtipos pymeDtiposByFacEstado) {
		this.pymeDtiposByFacEstado = pymeDtiposByFacEstado;
	}

	public PymeProyecto getPymeProyecto() {
		return this.pymeProyecto;
	}

	public void setPymeProyecto(PymeProyecto pymeProyecto) {
		this.pymeProyecto = pymeProyecto;
	}

	public PymeDtipos getPymeDtiposByFacTipoFacnd() {
		return this.pymeDtiposByFacTipoFacnd;
	}

	public void setPymeDtiposByFacTipoFacnd(PymeDtipos pymeDtiposByFacTipoFacnd) {
		this.pymeDtiposByFacTipoFacnd = pymeDtiposByFacTipoFacnd;
	}

	public PymeDtipos getPymeDtiposByFacTipoDoc() {
		return this.pymeDtiposByFacTipoDoc;
	}

	public void setPymeDtiposByFacTipoDoc(PymeDtipos pymeDtiposByFacTipoDoc) {
		this.pymeDtiposByFacTipoDoc = pymeDtiposByFacTipoDoc;
	}

	public long getFacConsectivo() {
		return this.facConsectivo;
	}

	public void setFacConsectivo(long facConsectivo) {
		this.facConsectivo = facConsectivo;
	}

	public BigDecimal getIdSoc() {
		return this.idSoc;
	}

	public void setIdSoc(BigDecimal idSoc) {
		this.idSoc = idSoc;
	}

	public String getFacSocNombre() {
		return this.facSocNombre;
	}

	public void setFacSocNombre(String facSocNombre) {
		this.facSocNombre = facSocNombre;
	}

	public BigDecimal getFacTotalLocal() {
		return this.facTotalLocal;
	}

	public void setFacTotalLocal(BigDecimal facTotalLocal) {
		this.facTotalLocal = facTotalLocal;
	}

	public BigDecimal getFacTotalExtranjero() {
		return this.facTotalExtranjero;
	}

	public void setFacTotalExtranjero(BigDecimal facTotalExtranjero) {
		this.facTotalExtranjero = facTotalExtranjero;
	}

	public String getFacTipoCambio() {
		return this.facTipoCambio;
	}

	public void setFacTipoCambio(String facTipoCambio) {
		this.facTipoCambio = facTipoCambio;
	}

	public Date getFacFechaDoc() {
		return this.facFechaDoc;
	}

	public void setFacFechaDoc(Date facFechaDoc) {
		this.facFechaDoc = facFechaDoc;
	}

	public Date getFacContabilizacion() {
		return this.facContabilizacion;
	}

	public void setFacContabilizacion(Date facContabilizacion) {
		this.facContabilizacion = facContabilizacion;
	}

	public Long getFacDocBase() {
		return this.facDocBase;
	}

	public void setFacDocBase(Long facDocBase) {
		this.facDocBase = facDocBase;
	}

	public Long getFacDocDestino() {
		return this.facDocDestino;
	}

	public void setFacDocDestino(Long facDocDestino) {
		this.facDocDestino = facDocDestino;
	}

	public String getFacComentarios() {
		return this.facComentarios;
	}

	public void setFacComentarios(String facComentarios) {
		this.facComentarios = facComentarios;
	}

	public Set<PymeFacncDetCli> getPymeFacncDetClis() {
		return this.pymeFacncDetClis;
	}

	public void setPymeFacncDetClis(Set<PymeFacncDetCli> pymeFacncDetClis) {
		this.pymeFacncDetClis = pymeFacncDetClis;
	}

}
