package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PymeSocios generated by hbm2java
 */
public class PymeSocios implements java.io.Serializable {

	private BigDecimal socId;
	private PymeDtipos pymeDtiposBySocTipoSocio;
	private PymeDtipos pymeDtiposBySocTipoPlazo;
	private PymeDtipos pymeDtiposBySocTipoCredito;
	private PymeDtipos pymeDtiposBySocGrupoClientes;
	private String socExterno;
	private String socNombre;
	private String socApellido1;
	private String socApellido2;
	private String socDireccion1;
	private String socDireccion2;
	private String socCreadoPor;
	private Date socCreadoEl;

	public PymeSocios() {
	}

	public PymeSocios(BigDecimal socId, PymeDtipos pymeDtiposBySocTipoSocio, PymeDtipos pymeDtiposBySocTipoCredito,
			String socExterno, String socNombre, String socApellido1) {
		this.socId = socId;
		this.pymeDtiposBySocTipoSocio = pymeDtiposBySocTipoSocio;
		this.pymeDtiposBySocTipoCredito = pymeDtiposBySocTipoCredito;
		this.socExterno = socExterno;
		this.socNombre = socNombre;
		this.socApellido1 = socApellido1;
	}

	public PymeSocios(BigDecimal socId, PymeDtipos pymeDtiposBySocTipoSocio, PymeDtipos pymeDtiposBySocTipoPlazo,
			PymeDtipos pymeDtiposBySocTipoCredito, PymeDtipos pymeDtiposBySocGrupoClientes, String socExterno,
			String socNombre, String socApellido1, String socApellido2, String socDireccion1, String socDireccion2,
			String socCreadoPor, Date socCreadoEl) {
		this.socId = socId;
		this.pymeDtiposBySocTipoSocio = pymeDtiposBySocTipoSocio;
		this.pymeDtiposBySocTipoPlazo = pymeDtiposBySocTipoPlazo;
		this.pymeDtiposBySocTipoCredito = pymeDtiposBySocTipoCredito;
		this.pymeDtiposBySocGrupoClientes = pymeDtiposBySocGrupoClientes;
		this.socExterno = socExterno;
		this.socNombre = socNombre;
		this.socApellido1 = socApellido1;
		this.socApellido2 = socApellido2;
		this.socDireccion1 = socDireccion1;
		this.socDireccion2 = socDireccion2;
		this.socCreadoPor = socCreadoPor;
		this.socCreadoEl = socCreadoEl;
	}

	public BigDecimal getSocId() {
		return this.socId;
	}

	public void setSocId(BigDecimal socId) {
		this.socId = socId;
	}

	public PymeDtipos getPymeDtiposBySocTipoSocio() {
		return this.pymeDtiposBySocTipoSocio;
	}

	public void setPymeDtiposBySocTipoSocio(PymeDtipos pymeDtiposBySocTipoSocio) {
		this.pymeDtiposBySocTipoSocio = pymeDtiposBySocTipoSocio;
	}

	public PymeDtipos getPymeDtiposBySocTipoPlazo() {
		return this.pymeDtiposBySocTipoPlazo;
	}

	public void setPymeDtiposBySocTipoPlazo(PymeDtipos pymeDtiposBySocTipoPlazo) {
		this.pymeDtiposBySocTipoPlazo = pymeDtiposBySocTipoPlazo;
	}

	public PymeDtipos getPymeDtiposBySocTipoCredito() {
		return this.pymeDtiposBySocTipoCredito;
	}

	public void setPymeDtiposBySocTipoCredito(PymeDtipos pymeDtiposBySocTipoCredito) {
		this.pymeDtiposBySocTipoCredito = pymeDtiposBySocTipoCredito;
	}

	public PymeDtipos getPymeDtiposBySocGrupoClientes() {
		return this.pymeDtiposBySocGrupoClientes;
	}

	public void setPymeDtiposBySocGrupoClientes(PymeDtipos pymeDtiposBySocGrupoClientes) {
		this.pymeDtiposBySocGrupoClientes = pymeDtiposBySocGrupoClientes;
	}

	public String getSocExterno() {
		return this.socExterno;
	}

	public void setSocExterno(String socExterno) {
		this.socExterno = socExterno;
	}

	public String getSocNombre() {
		return this.socNombre;
	}

	public void setSocNombre(String socNombre) {
		this.socNombre = socNombre;
	}

	public String getSocApellido1() {
		return this.socApellido1;
	}

	public void setSocApellido1(String socApellido1) {
		this.socApellido1 = socApellido1;
	}

	public String getSocApellido2() {
		return this.socApellido2;
	}

	public void setSocApellido2(String socApellido2) {
		this.socApellido2 = socApellido2;
	}

	public String getSocDireccion1() {
		return this.socDireccion1;
	}

	public void setSocDireccion1(String socDireccion1) {
		this.socDireccion1 = socDireccion1;
	}

	public String getSocDireccion2() {
		return this.socDireccion2;
	}

	public void setSocDireccion2(String socDireccion2) {
		this.socDireccion2 = socDireccion2;
	}

	public String getSocCreadoPor() {
		return this.socCreadoPor;
	}

	public void setSocCreadoPor(String socCreadoPor) {
		this.socCreadoPor = socCreadoPor;
	}

	public Date getSocCreadoEl() {
		return this.socCreadoEl;
	}

	public void setSocCreadoEl(Date socCreadoEl) {
		this.socCreadoEl = socCreadoEl;
	}

}
