package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeMentradas generated by hbm2java
 */
public class PymeMentradas implements java.io.Serializable {

	private BigDecimal mentId;
	private PymeSubetapa pymeSubetapa;
	private Date creadoEl;
	private String creadoPor;
	private Set<PymeDentradas> pymeDentradases = new HashSet<PymeDentradas>(0);

	public PymeMentradas() {
	}

	public PymeMentradas(BigDecimal mentId, PymeSubetapa pymeSubetapa) {
		this.mentId = mentId;
		this.pymeSubetapa = pymeSubetapa;
	}

	public PymeMentradas(BigDecimal mentId, PymeSubetapa pymeSubetapa, Date creadoEl, String creadoPor,
			Set<PymeDentradas> pymeDentradases) {
		this.mentId = mentId;
		this.pymeSubetapa = pymeSubetapa;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.pymeDentradases = pymeDentradases;
	}

	public BigDecimal getMentId() {
		return this.mentId;
	}

	public void setMentId(BigDecimal mentId) {
		this.mentId = mentId;
	}

	public PymeSubetapa getPymeSubetapa() {
		return this.pymeSubetapa;
	}

	public void setPymeSubetapa(PymeSubetapa pymeSubetapa) {
		this.pymeSubetapa = pymeSubetapa;
	}

	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	public String getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

	public Set<PymeDentradas> getPymeDentradases() {
		return this.pymeDentradases;
	}

	public void setPymeDentradases(Set<PymeDentradas> pymeDentradases) {
		this.pymeDentradases = pymeDentradases;
	}

}
