package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

/**
 * PymeConsecutivos generated by hbm2java
 */
public class PymeConsecutivos implements java.io.Serializable {

	private long consId;
	private long consTipodoc;
	private long consInicial;
	private long consActual;
	private long consFinal;
	private long proyId;

	public PymeConsecutivos() {
	}

	public PymeConsecutivos(long consId, long consTipodoc, long consInicial, long consActual, long consFinal,
			long proyId) {
		this.consId = consId;
		this.consTipodoc = consTipodoc;
		this.consInicial = consInicial;
		this.consActual = consActual;
		this.consFinal = consFinal;
		this.proyId = proyId;
	}

	public long getConsId() {
		return this.consId;
	}

	public void setConsId(long consId) {
		this.consId = consId;
	}

	public long getConsTipodoc() {
		return this.consTipodoc;
	}

	public void setConsTipodoc(long consTipodoc) {
		this.consTipodoc = consTipodoc;
	}

	public long getConsInicial() {
		return this.consInicial;
	}

	public void setConsInicial(long consInicial) {
		this.consInicial = consInicial;
	}

	public long getConsActual() {
		return this.consActual;
	}

	public void setConsActual(long consActual) {
		this.consActual = consActual;
	}

	public long getConsFinal() {
		return this.consFinal;
	}

	public void setConsFinal(long consFinal) {
		this.consFinal = consFinal;
	}

	public long getProyId() {
		return this.proyId;
	}

	public void setProyId(long proyId) {
		this.proyId = proyId;
	}

}
