package com.gotn.entity;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeEmpresa generated by hbm2java
 */
public class PymeEmpresa implements java.io.Serializable {

	private long empId;
	private PymeDtipos pymeDtipos;
	private String empNombre;
	private String empNombreImpreso;
	private byte empIdJuridico;
	private String empNombreRepresentante;
	private String empDireccion;
	private String empTelefono1;
	private String empTelefono2;
	private String empFax;
	private String empEmail;
	private String empRutaLogo;
	private String empCreadoPor;
	private Date creadoEl;
	private BigDecimal empImpuestoVentas;
	private Set<PymeProyecto> pymeProyectos = new HashSet<PymeProyecto>(0);
	private Set<PymeSysUsers> pymeSysUserses = new HashSet<PymeSysUsers>(0);

	public PymeEmpresa() {
	}

	public PymeEmpresa(long empId, PymeDtipos pymeDtipos, String empNombre, byte empIdJuridico, String empDireccion,
			String empTelefono1, String empCreadoPor, BigDecimal empImpuestoVentas) {
		this.empId = empId;
		this.pymeDtipos = pymeDtipos;
		this.empNombre = empNombre;
		this.empIdJuridico = empIdJuridico;
		this.empDireccion = empDireccion;
		this.empTelefono1 = empTelefono1;
		this.empCreadoPor = empCreadoPor;
		this.empImpuestoVentas = empImpuestoVentas;
	}

	public PymeEmpresa(long empId, PymeDtipos pymeDtipos, String empNombre, String empNombreImpreso, byte empIdJuridico,
			String empNombreRepresentante, String empDireccion, String empTelefono1, String empTelefono2, String empFax,
			String empEmail, String empRutaLogo, String empCreadoPor, Date creadoEl, BigDecimal empImpuestoVentas,
			Set<PymeProyecto> pymeProyectos, Set<PymeSysUsers> pymeSysUserses) {
		this.empId = empId;
		this.pymeDtipos = pymeDtipos;
		this.empNombre = empNombre;
		this.empNombreImpreso = empNombreImpreso;
		this.empIdJuridico = empIdJuridico;
		this.empNombreRepresentante = empNombreRepresentante;
		this.empDireccion = empDireccion;
		this.empTelefono1 = empTelefono1;
		this.empTelefono2 = empTelefono2;
		this.empFax = empFax;
		this.empEmail = empEmail;
		this.empRutaLogo = empRutaLogo;
		this.empCreadoPor = empCreadoPor;
		this.creadoEl = creadoEl;
		this.empImpuestoVentas = empImpuestoVentas;
		this.pymeProyectos = pymeProyectos;
		this.pymeSysUserses = pymeSysUserses;
	}

	public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}

	public PymeDtipos getPymeDtipos() {
		return this.pymeDtipos;
	}

	public void setPymeDtipos(PymeDtipos pymeDtipos) {
		this.pymeDtipos = pymeDtipos;
	}

	public String getEmpNombre() {
		return this.empNombre;
	}

	public void setEmpNombre(String empNombre) {
		this.empNombre = empNombre;
	}

	public String getEmpNombreImpreso() {
		return this.empNombreImpreso;
	}

	public void setEmpNombreImpreso(String empNombreImpreso) {
		this.empNombreImpreso = empNombreImpreso;
	}

	public byte getEmpIdJuridico() {
		return this.empIdJuridico;
	}

	public void setEmpIdJuridico(byte empIdJuridico) {
		this.empIdJuridico = empIdJuridico;
	}

	public String getEmpNombreRepresentante() {
		return this.empNombreRepresentante;
	}

	public void setEmpNombreRepresentante(String empNombreRepresentante) {
		this.empNombreRepresentante = empNombreRepresentante;
	}

	public String getEmpDireccion() {
		return this.empDireccion;
	}

	public void setEmpDireccion(String empDireccion) {
		this.empDireccion = empDireccion;
	}

	public String getEmpTelefono1() {
		return this.empTelefono1;
	}

	public void setEmpTelefono1(String empTelefono1) {
		this.empTelefono1 = empTelefono1;
	}

	public String getEmpTelefono2() {
		return this.empTelefono2;
	}

	public void setEmpTelefono2(String empTelefono2) {
		this.empTelefono2 = empTelefono2;
	}

	public String getEmpFax() {
		return this.empFax;
	}

	public void setEmpFax(String empFax) {
		this.empFax = empFax;
	}

	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	public String getEmpRutaLogo() {
		return this.empRutaLogo;
	}

	public void setEmpRutaLogo(String empRutaLogo) {
		this.empRutaLogo = empRutaLogo;
	}

	public String getEmpCreadoPor() {
		return this.empCreadoPor;
	}

	public void setEmpCreadoPor(String empCreadoPor) {
		this.empCreadoPor = empCreadoPor;
	}

	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	public BigDecimal getEmpImpuestoVentas() {
		return this.empImpuestoVentas;
	}

	public void setEmpImpuestoVentas(BigDecimal empImpuestoVentas) {
		this.empImpuestoVentas = empImpuestoVentas;
	}

	public Set<PymeProyecto> getPymeProyectos() {
		return this.pymeProyectos;
	}

	public void setPymeProyectos(Set<PymeProyecto> pymeProyectos) {
		this.pymeProyectos = pymeProyectos;
	}

	public Set<PymeSysUsers> getPymeSysUserses() {
		return this.pymeSysUserses;
	}

	public void setPymeSysUserses(Set<PymeSysUsers> pymeSysUserses) {
		this.pymeSysUserses = pymeSysUserses;
	}

}
