package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeTipoCambio generated by hbm2java
 */
@Entity
@Table(name = "PYME_TIPO_CAMBIO")
public class PymeTipoCambio implements java.io.Serializable {

	private long tcId;
	private double tcCompra;
	private String tcMoneda;
	private Date tcFecha;

	public PymeTipoCambio() {
	}

	public PymeTipoCambio(long tcId, double tcCompra, Date tcFecha) {
		this.tcId = tcId;
		this.tcCompra = tcCompra;
		this.tcFecha = tcFecha;
	}

	public PymeTipoCambio(long tcId, double tcCompra, String tcMoneda, Date tcFecha) {
		this.tcId = tcId;
		this.tcCompra = tcCompra;
		this.tcMoneda = tcMoneda;
		this.tcFecha = tcFecha;
	}

	@Id

	@Column(name = "TC_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public long getTcId() {
		return this.tcId;
	}

	public void setTcId(long tcId) {
		this.tcId = tcId;
	}

	@Column(name = "TC_COMPRA", nullable = false, precision = 18, scale = 3)
	public double getTcCompra() {
		return this.tcCompra;
	}

	public void setTcCompra(double d) {
		this.tcCompra = d;
	}

	@Column(name = "TC_MONEDA", length = 10)
	public String getTcMoneda() {
		return this.tcMoneda;
	}

	public void setTcMoneda(String tcMoneda) {
		this.tcMoneda = tcMoneda;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TC_FECHA", nullable = false, length = 7)
	public Date getTcFecha() {
		return this.tcFecha;
	}

	public void setTcFecha(Date tcFecha) {
		this.tcFecha = tcFecha;
	}

}
