package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeFacncDetProv generated by hbm2java
 */
@Entity
@Table(name = "PYME_FACNC_DET_PROV")
public class PymeFacncDetProv implements java.io.Serializable {

	private long facprovdId;
	private PymeProductos pymeProductos;
	private PymeFacncEncProv pymeFacncEncProv;
	private Long facprovdCantidad;
	private String facprovdDetalle;
	private BigDecimal facprovdTotalLineaLocal;
	private String facprovdTotalLineaExt;
	private String facprovdCreadoPor;
	private Date facprovdCreadoEl;

	public PymeFacncDetProv() {
	}

	public PymeFacncDetProv(long facprovdId, PymeFacncEncProv pymeFacncEncProv) {
		this.facprovdId = facprovdId;
		this.pymeFacncEncProv = pymeFacncEncProv;
	}

	public PymeFacncDetProv(long facprovdId, PymeProductos pymeProductos, PymeFacncEncProv pymeFacncEncProv,
			Long facprovdCantidad, String facprovdDetalle, BigDecimal facprovdTotalLineaLocal,
			String facprovdTotalLineaExt, String facprovdCreadoPor, Date facprovdCreadoEl) {
		this.facprovdId = facprovdId;
		this.pymeProductos = pymeProductos;
		this.pymeFacncEncProv = pymeFacncEncProv;
		this.facprovdCantidad = facprovdCantidad;
		this.facprovdDetalle = facprovdDetalle;
		this.facprovdTotalLineaLocal = facprovdTotalLineaLocal;
		this.facprovdTotalLineaExt = facprovdTotalLineaExt;
		this.facprovdCreadoPor = facprovdCreadoPor;
		this.facprovdCreadoEl = facprovdCreadoEl;
	}

	@Id

	@Column(name = "FACPROVD_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getFacprovdId() {
		return this.facprovdId;
	}

	public void setFacprovdId(long facprovdId) {
		this.facprovdId = facprovdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUC_ID")
	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACPROV_ID", nullable = false)
	public PymeFacncEncProv getPymeFacncEncProv() {
		return this.pymeFacncEncProv;
	}

	public void setPymeFacncEncProv(PymeFacncEncProv pymeFacncEncProv) {
		this.pymeFacncEncProv = pymeFacncEncProv;
	}

	@Column(name = "FACPROVD_CANTIDAD", precision = 10, scale = 0)
	public Long getFacprovdCantidad() {
		return this.facprovdCantidad;
	}

	public void setFacprovdCantidad(Long facprovdCantidad) {
		this.facprovdCantidad = facprovdCantidad;
	}

	@Column(name = "FACPROVD_DETALLE", length = 100)
	public String getFacprovdDetalle() {
		return this.facprovdDetalle;
	}

	public void setFacprovdDetalle(String facprovdDetalle) {
		this.facprovdDetalle = facprovdDetalle;
	}

	@Column(name = "FACPROVD_TOTAL_LINEA_LOCAL", precision = 18, scale = 3)
	public BigDecimal getFacprovdTotalLineaLocal() {
		return this.facprovdTotalLineaLocal;
	}

	public void setFacprovdTotalLineaLocal(BigDecimal facprovdTotalLineaLocal) {
		this.facprovdTotalLineaLocal = facprovdTotalLineaLocal;
	}

	@Column(name = "FACPROVD_TOTAL_LINEA_EXT", length = 20)
	public String getFacprovdTotalLineaExt() {
		return this.facprovdTotalLineaExt;
	}

	public void setFacprovdTotalLineaExt(String facprovdTotalLineaExt) {
		this.facprovdTotalLineaExt = facprovdTotalLineaExt;
	}

	@Column(name = "FACPROVD_CREADO_POR", length = 50)
	public String getFacprovdCreadoPor() {
		return this.facprovdCreadoPor;
	}

	public void setFacprovdCreadoPor(String facprovdCreadoPor) {
		this.facprovdCreadoPor = facprovdCreadoPor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FACPROVD_CREADO_EL", length = 7)
	public Date getFacprovdCreadoEl() {
		return this.facprovdCreadoEl;
	}

	public void setFacprovdCreadoEl(Date facprovdCreadoEl) {
		this.facprovdCreadoEl = facprovdCreadoEl;
	}

}
