package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * PymeDlistaPrecios generated by hbm2java
 */
public class PymeDlistaPrecios implements java.io.Serializable {

	private long dlistaId;
	private PymeMlistaPrecios pymeMlistaPrecios;
	private long producId;
	private BigDecimal dlistaPrecio;

	public PymeDlistaPrecios() {
	}

	public PymeDlistaPrecios(long dlistaId, PymeMlistaPrecios pymeMlistaPrecios, long producId,
			BigDecimal dlistaPrecio) {
		this.dlistaId = dlistaId;
		this.pymeMlistaPrecios = pymeMlistaPrecios;
		this.producId = producId;
		this.dlistaPrecio = dlistaPrecio;
	}

	public long getDlistaId() {
		return this.dlistaId;
	}

	public void setDlistaId(long dlistaId) {
		this.dlistaId = dlistaId;
	}

	public PymeMlistaPrecios getPymeMlistaPrecios() {
		return this.pymeMlistaPrecios;
	}

	public void setPymeMlistaPrecios(PymeMlistaPrecios pymeMlistaPrecios) {
		this.pymeMlistaPrecios = pymeMlistaPrecios;
	}

	public long getProducId() {
		return this.producId;
	}

	public void setProducId(long producId) {
		this.producId = producId;
	}

	public BigDecimal getDlistaPrecio() {
		return this.dlistaPrecio;
	}

	public void setDlistaPrecio(BigDecimal dlistaPrecio) {
		this.dlistaPrecio = dlistaPrecio;
	}

}
