package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PymeDtipos generated by hbm2java
 */
@Entity
@Table(name = "PYME_DTIPOS", uniqueConstraints = @UniqueConstraint(columnNames = { "MTIPO_ID", "DTIPO_NOMBRE" }))
public class PymeDtipos implements java.io.Serializable {

	private long dtipoId;
	private long mtipoId;
	private String dtipoNombre;
	private boolean dtipoEstado;
	private Date dtipoCreadoEl;
	private BigDecimal dtipoCantidad;

	public PymeDtipos() {
	}

	public PymeDtipos(long dtipoId, long mtipoId, String dtipoNombre, boolean dtipoEstado, Date dtipoCreadoEl) {
		this.dtipoId = dtipoId;
		this.mtipoId = mtipoId;
		this.dtipoNombre = dtipoNombre;
		this.dtipoEstado = dtipoEstado;
		this.dtipoCreadoEl = dtipoCreadoEl;
	}

	public PymeDtipos(long dtipoId, long mtipoId, String dtipoNombre, boolean dtipoEstado, Date dtipoCreadoEl,
			BigDecimal dtipoCantidad) {
		this.dtipoId = dtipoId;
		this.mtipoId = mtipoId;
		this.dtipoNombre = dtipoNombre;
		this.dtipoEstado = dtipoEstado;
		this.dtipoCreadoEl = dtipoCreadoEl;
		this.dtipoCantidad = dtipoCantidad;
	}

	@Id

	@Column(name = "DTIPO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDtipoId() {
		return this.dtipoId;
	}

	public void setDtipoId(long dtipoId) {
		this.dtipoId = dtipoId;
	}

	@Column(name = "MTIPO_ID", nullable = false, precision = 10, scale = 0)
	public long getMtipoId() {
		return this.mtipoId;
	}

	public void setMtipoId(long mtipoId) {
		this.mtipoId = mtipoId;
	}

	@Column(name = "DTIPO_NOMBRE", nullable = false, length = 50)
	public String getDtipoNombre() {
		return this.dtipoNombre;
	}

	public void setDtipoNombre(String dtipoNombre) {
		this.dtipoNombre = dtipoNombre;
	}

	@Column(name = "DTIPO_ESTADO", nullable = false, precision = 1, scale = 0)
	public boolean isDtipoEstado() {
		return this.dtipoEstado;
	}

	public void setDtipoEstado(boolean dtipoEstado) {
		this.dtipoEstado = dtipoEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTIPO_CREADO_EL", nullable = false, length = 7)
	public Date getDtipoCreadoEl() {
		return this.dtipoCreadoEl;
	}

	public void setDtipoCreadoEl(Date dtipoCreadoEl) {
		this.dtipoCreadoEl = dtipoCreadoEl;
	}

	@Column(name = "DTIPO_CANTIDAD", precision = 22, scale = 0)
	public BigDecimal getDtipoCantidad() {
		return this.dtipoCantidad;
	}

	public void setDtipoCantidad(BigDecimal dtipoCantidad) {
		this.dtipoCantidad = dtipoCantidad;
	}

}
