package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeFacncEncCli generated by hbm2java
 */
@Entity
@Table(name = "PYME_FACNC_ENC_CLI")
public class PymeFacncEncCli implements java.io.Serializable {

	private long facId;
	private PymeProyecto pymeProyecto;
	private long facConsectivo;
	private BigDecimal idSoc;
	private String facSocNombre;
	private BigDecimal facTotalLocal;
	private BigDecimal facTotalExtranjero;
	private String facTipoCambio;
	private Date facFechaDoc;
	private Date facContabilizacion;
	private Long facDocBase;
	private Long facDocDestino;
	private long facTipoDoc;
	private BigDecimal facEstado;
	private String facComentarios;
	private long facTipoFacnd;
	private Set<PymeFacncDetCli> pymeFacncDetClis = new HashSet<PymeFacncDetCli>(0);

	public PymeFacncEncCli() {
	}

	public PymeFacncEncCli(long facId, PymeProyecto pymeProyecto, long facConsectivo, long facTipoDoc,
			BigDecimal facEstado, long facTipoFacnd) {
		this.facId = facId;
		this.pymeProyecto = pymeProyecto;
		this.facConsectivo = facConsectivo;
		this.facTipoDoc = facTipoDoc;
		this.facEstado = facEstado;
		this.facTipoFacnd = facTipoFacnd;
	}

	public PymeFacncEncCli(long facId, PymeProyecto pymeProyecto, long facConsectivo, BigDecimal idSoc,
			String facSocNombre, BigDecimal facTotalLocal, BigDecimal facTotalExtranjero, String facTipoCambio,
			Date facFechaDoc, Date facContabilizacion, Long facDocBase, Long facDocDestino, long facTipoDoc,
			BigDecimal facEstado, String facComentarios, long facTipoFacnd, Set<PymeFacncDetCli> pymeFacncDetClis) {
		this.facId = facId;
		this.pymeProyecto = pymeProyecto;
		this.facConsectivo = facConsectivo;
		this.idSoc = idSoc;
		this.facSocNombre = facSocNombre;
		this.facTotalLocal = facTotalLocal;
		this.facTotalExtranjero = facTotalExtranjero;
		this.facTipoCambio = facTipoCambio;
		this.facFechaDoc = facFechaDoc;
		this.facContabilizacion = facContabilizacion;
		this.facDocBase = facDocBase;
		this.facDocDestino = facDocDestino;
		this.facTipoDoc = facTipoDoc;
		this.facEstado = facEstado;
		this.facComentarios = facComentarios;
		this.facTipoFacnd = facTipoFacnd;
		this.pymeFacncDetClis = pymeFacncDetClis;
	}

	@Id

	@Column(name = "FAC_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public long getFacId() {
		return this.facId;
	}

	public void setFacId(long facId) {
		this.facId = facId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROY_ID", nullable = false)
	public PymeProyecto getPymeProyecto() {
		return this.pymeProyecto;
	}

	public void setPymeProyecto(PymeProyecto pymeProyecto) {
		this.pymeProyecto = pymeProyecto;
	}

	@Column(name = "FAC_CONSECTIVO", nullable = false, precision = 18, scale = 0)
	public long getFacConsectivo() {
		return this.facConsectivo;
	}

	public void setFacConsectivo(long facConsectivo) {
		this.facConsectivo = facConsectivo;
	}

	@Column(name = "ID_SOC", precision = 22, scale = 0)
	public BigDecimal getIdSoc() {
		return this.idSoc;
	}

	public void setIdSoc(BigDecimal idSoc) {
		this.idSoc = idSoc;
	}

	@Column(name = "FAC_SOC_NOMBRE", length = 200)
	public String getFacSocNombre() {
		return this.facSocNombre;
	}

	public void setFacSocNombre(String facSocNombre) {
		this.facSocNombre = facSocNombre;
	}

	@Column(name = "FAC_TOTAL_LOCAL", precision = 18, scale = 3)
	public BigDecimal getFacTotalLocal() {
		return this.facTotalLocal;
	}

	public void setFacTotalLocal(BigDecimal facTotalLocal) {
		this.facTotalLocal = facTotalLocal;
	}

	@Column(name = "FAC_TOTAL_EXTRANJERO", precision = 18, scale = 3)
	public BigDecimal getFacTotalExtranjero() {
		return this.facTotalExtranjero;
	}

	public void setFacTotalExtranjero(BigDecimal facTotalExtranjero) {
		this.facTotalExtranjero = facTotalExtranjero;
	}

	@Column(name = "FAC_TIPO_CAMBIO", length = 20)
	public String getFacTipoCambio() {
		return this.facTipoCambio;
	}

	public void setFacTipoCambio(String facTipoCambio) {
		this.facTipoCambio = facTipoCambio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FAC_FECHA_DOC", length = 7)
	public Date getFacFechaDoc() {
		return this.facFechaDoc;
	}

	public void setFacFechaDoc(Date facFechaDoc) {
		this.facFechaDoc = facFechaDoc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FAC_CONTABILIZACION", length = 7)
	public Date getFacContabilizacion() {
		return this.facContabilizacion;
	}

	public void setFacContabilizacion(Date facContabilizacion) {
		this.facContabilizacion = facContabilizacion;
	}

	@Column(name = "FAC_DOC_BASE", precision = 18, scale = 0)
	public Long getFacDocBase() {
		return this.facDocBase;
	}

	public void setFacDocBase(Long facDocBase) {
		this.facDocBase = facDocBase;
	}

	@Column(name = "FAC_DOC_DESTINO", precision = 18, scale = 0)
	public Long getFacDocDestino() {
		return this.facDocDestino;
	}

	public void setFacDocDestino(Long facDocDestino) {
		this.facDocDestino = facDocDestino;
	}

	@Column(name = "FAC_TIPO_DOC", nullable = false, precision = 10, scale = 0)
	public long getFacTipoDoc() {
		return this.facTipoDoc;
	}

	public void setFacTipoDoc(long facTipoDoc) {
		this.facTipoDoc = facTipoDoc;
	}

	@Column(name = "FAC_ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getFacEstado() {
		return this.facEstado;
	}

	public void setFacEstado(BigDecimal facEstado) {
		this.facEstado = facEstado;
	}

	@Column(name = "FAC_COMENTARIOS", length = 200)
	public String getFacComentarios() {
		return this.facComentarios;
	}

	public void setFacComentarios(String facComentarios) {
		this.facComentarios = facComentarios;
	}

	@Column(name = "FAC_TIPO_FACND", nullable = false, precision = 10, scale = 0)
	public long getFacTipoFacnd() {
		return this.facTipoFacnd;
	}

	public void setFacTipoFacnd(long facTipoFacnd) {
		this.facTipoFacnd = facTipoFacnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeFacncEncCli")
	public Set<PymeFacncDetCli> getPymeFacncDetClis() {
		return this.pymeFacncDetClis;
	}

	public void setPymeFacncDetClis(Set<PymeFacncDetCli> pymeFacncDetClis) {
		this.pymeFacncDetClis = pymeFacncDetClis;
	}

}
