package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeEtapa generated by hbm2java
 */
public class PymeEtapa implements java.io.Serializable {

	private long etaId;
	private PymeProyecto pymeProyecto;
	private PymeDtipos pymeDtipos;
	private String etaNombre;
	private String etaDescripcion;
	private Date creadoEl;
	private String creadoPor;
	private Set<PymeSubetapa> pymeSubetapas = new HashSet<PymeSubetapa>(0);

	public PymeEtapa() {
	}

	public PymeEtapa(long etaId, PymeProyecto pymeProyecto, String etaNombre) {
		this.etaId = etaId;
		this.pymeProyecto = pymeProyecto;
		this.etaNombre = etaNombre;
	}

	public PymeEtapa(long etaId, PymeProyecto pymeProyecto, PymeDtipos pymeDtipos, String etaNombre,
			String etaDescripcion, Date creadoEl, String creadoPor, Set<PymeSubetapa> pymeSubetapas) {
		this.etaId = etaId;
		this.pymeProyecto = pymeProyecto;
		this.pymeDtipos = pymeDtipos;
		this.etaNombre = etaNombre;
		this.etaDescripcion = etaDescripcion;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.pymeSubetapas = pymeSubetapas;
	}

	public long getEtaId() {
		return this.etaId;
	}

	public void setEtaId(long etaId) {
		this.etaId = etaId;
	}

	public PymeProyecto getPymeProyecto() {
		return this.pymeProyecto;
	}

	public void setPymeProyecto(PymeProyecto pymeProyecto) {
		this.pymeProyecto = pymeProyecto;
	}

	public PymeDtipos getPymeDtipos() {
		return this.pymeDtipos;
	}

	public void setPymeDtipos(PymeDtipos pymeDtipos) {
		this.pymeDtipos = pymeDtipos;
	}

	public String getEtaNombre() {
		return this.etaNombre;
	}

	public void setEtaNombre(String etaNombre) {
		this.etaNombre = etaNombre;
	}

	public String getEtaDescripcion() {
		return this.etaDescripcion;
	}

	public void setEtaDescripcion(String etaDescripcion) {
		this.etaDescripcion = etaDescripcion;
	}

	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	public String getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

	public Set<PymeSubetapa> getPymeSubetapas() {
		return this.pymeSubetapas;
	}

	public void setPymeSubetapas(Set<PymeSubetapa> pymeSubetapas) {
		this.pymeSubetapas = pymeSubetapas;
	}

}
