package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PymeSocios generated by hbm2java
 */
@Entity
@Table(name = "PYME_SOCIOS", uniqueConstraints = @UniqueConstraint(columnNames = "SOC_EXTERNO"))
public class PymeSocios implements java.io.Serializable {

	private BigDecimal socId;
	private PymeDtipos pymeDtiposBySocTipoSocio;
	private PymeDtipos pymeDtiposBySocTipoPlazo;
	private PymeDtipos pymeDtiposBySocTipoCredito;
	private PymeDtipos pymeDtiposBySocGrupoClientes;
	private String socExterno;
	private String socNombre;
	private String socApellido1;
	private String socApellido2;
	private String socDireccion1;
	private String socDireccion2;
	private String socCreadoPor;
	private Date socCreadoEl;

	public PymeSocios() {
	}

	public PymeSocios(BigDecimal socId, PymeDtipos pymeDtiposBySocTipoSocio, PymeDtipos pymeDtiposBySocTipoCredito,
			String socExterno, String socNombre, String socApellido1) {
		this.socId = socId;
		this.pymeDtiposBySocTipoSocio = pymeDtiposBySocTipoSocio;
		this.pymeDtiposBySocTipoCredito = pymeDtiposBySocTipoCredito;
		this.socExterno = socExterno;
		this.socNombre = socNombre;
		this.socApellido1 = socApellido1;
	}

	public PymeSocios(BigDecimal socId, PymeDtipos pymeDtiposBySocTipoSocio, PymeDtipos pymeDtiposBySocTipoPlazo,
			PymeDtipos pymeDtiposBySocTipoCredito, PymeDtipos pymeDtiposBySocGrupoClientes, String socExterno,
			String socNombre, String socApellido1, String socApellido2, String socDireccion1, String socDireccion2,
			String socCreadoPor, Date socCreadoEl) {
		this.socId = socId;
		this.pymeDtiposBySocTipoSocio = pymeDtiposBySocTipoSocio;
		this.pymeDtiposBySocTipoPlazo = pymeDtiposBySocTipoPlazo;
		this.pymeDtiposBySocTipoCredito = pymeDtiposBySocTipoCredito;
		this.pymeDtiposBySocGrupoClientes = pymeDtiposBySocGrupoClientes;
		this.socExterno = socExterno;
		this.socNombre = socNombre;
		this.socApellido1 = socApellido1;
		this.socApellido2 = socApellido2;
		this.socDireccion1 = socDireccion1;
		this.socDireccion2 = socDireccion2;
		this.socCreadoPor = socCreadoPor;
		this.socCreadoEl = socCreadoEl;
	}

	@Id

	@Column(name = "SOC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSocId() {
		return this.socId;
	}

	public void setSocId(BigDecimal socId) {
		this.socId = socId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOC_TIPO_SOCIO", nullable = false)
	public PymeDtipos getPymeDtiposBySocTipoSocio() {
		return this.pymeDtiposBySocTipoSocio;
	}

	public void setPymeDtiposBySocTipoSocio(PymeDtipos pymeDtiposBySocTipoSocio) {
		this.pymeDtiposBySocTipoSocio = pymeDtiposBySocTipoSocio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOC_TIPO_PLAZO")
	public PymeDtipos getPymeDtiposBySocTipoPlazo() {
		return this.pymeDtiposBySocTipoPlazo;
	}

	public void setPymeDtiposBySocTipoPlazo(PymeDtipos pymeDtiposBySocTipoPlazo) {
		this.pymeDtiposBySocTipoPlazo = pymeDtiposBySocTipoPlazo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOC_TIPO_CREDITO", nullable = false)
	public PymeDtipos getPymeDtiposBySocTipoCredito() {
		return this.pymeDtiposBySocTipoCredito;
	}

	public void setPymeDtiposBySocTipoCredito(PymeDtipos pymeDtiposBySocTipoCredito) {
		this.pymeDtiposBySocTipoCredito = pymeDtiposBySocTipoCredito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOC_GRUPO_CLIENTES")
	public PymeDtipos getPymeDtiposBySocGrupoClientes() {
		return this.pymeDtiposBySocGrupoClientes;
	}

	public void setPymeDtiposBySocGrupoClientes(PymeDtipos pymeDtiposBySocGrupoClientes) {
		this.pymeDtiposBySocGrupoClientes = pymeDtiposBySocGrupoClientes;
	}

	@Column(name = "SOC_EXTERNO", unique = true, nullable = false, length = 50)
	public String getSocExterno() {
		return this.socExterno;
	}

	public void setSocExterno(String socExterno) {
		this.socExterno = socExterno;
	}

	@Column(name = "SOC_NOMBRE", nullable = false, length = 100)
	public String getSocNombre() {
		return this.socNombre;
	}

	public void setSocNombre(String socNombre) {
		this.socNombre = socNombre;
	}

	@Column(name = "SOC_APELLIDO1", nullable = false, length = 100)
	public String getSocApellido1() {
		return this.socApellido1;
	}

	public void setSocApellido1(String socApellido1) {
		this.socApellido1 = socApellido1;
	}

	@Column(name = "SOC_APELLIDO2", length = 100)
	public String getSocApellido2() {
		return this.socApellido2;
	}

	public void setSocApellido2(String socApellido2) {
		this.socApellido2 = socApellido2;
	}

	@Column(name = "SOC_DIRECCION1", length = 500)
	public String getSocDireccion1() {
		return this.socDireccion1;
	}

	public void setSocDireccion1(String socDireccion1) {
		this.socDireccion1 = socDireccion1;
	}

	@Column(name = "SOC_DIRECCION2", length = 500)
	public String getSocDireccion2() {
		return this.socDireccion2;
	}

	public void setSocDireccion2(String socDireccion2) {
		this.socDireccion2 = socDireccion2;
	}

	@Column(name = "SOC_CREADO_POR", length = 20)
	public String getSocCreadoPor() {
		return this.socCreadoPor;
	}

	public void setSocCreadoPor(String socCreadoPor) {
		this.socCreadoPor = socCreadoPor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SOC_CREADO_EL", length = 7)
	public Date getSocCreadoEl() {
		return this.socCreadoEl;
	}

	public void setSocCreadoEl(Date socCreadoEl) {
		this.socCreadoEl = socCreadoEl;
	}

}
