package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeNdDetProv generated by hbm2java
 */
@Entity
@Table(name = "PYME_ND_DET_PROV")
public class PymeNdDetProv implements java.io.Serializable {

	private long ndprovdId;
	private PymeNdEncProv pymeNdEncProv;
	private PymeProductos pymeProductos;
	private Long ndprovdCantidad;
	private String ndprovdDetalle;
	private BigDecimal ndprovdTotalLineaLocal;
	private String ndprovdTotalLineaExt;
	private String ndprovdCreadoPor;
	private Date ndprovdCreadoEl;

	public PymeNdDetProv() {
	}

	public PymeNdDetProv(long ndprovdId, PymeNdEncProv pymeNdEncProv) {
		this.ndprovdId = ndprovdId;
		this.pymeNdEncProv = pymeNdEncProv;
	}

	public PymeNdDetProv(long ndprovdId, PymeNdEncProv pymeNdEncProv, PymeProductos pymeProductos, Long ndprovdCantidad,
			String ndprovdDetalle, BigDecimal ndprovdTotalLineaLocal, String ndprovdTotalLineaExt,
			String ndprovdCreadoPor, Date ndprovdCreadoEl) {
		this.ndprovdId = ndprovdId;
		this.pymeNdEncProv = pymeNdEncProv;
		this.pymeProductos = pymeProductos;
		this.ndprovdCantidad = ndprovdCantidad;
		this.ndprovdDetalle = ndprovdDetalle;
		this.ndprovdTotalLineaLocal = ndprovdTotalLineaLocal;
		this.ndprovdTotalLineaExt = ndprovdTotalLineaExt;
		this.ndprovdCreadoPor = ndprovdCreadoPor;
		this.ndprovdCreadoEl = ndprovdCreadoEl;
	}

	@Id

	@Column(name = "NDPROVD_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getNdprovdId() {
		return this.ndprovdId;
	}

	public void setNdprovdId(long ndprovdId) {
		this.ndprovdId = ndprovdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NDPROV_ID", nullable = false)
	public PymeNdEncProv getPymeNdEncProv() {
		return this.pymeNdEncProv;
	}

	public void setPymeNdEncProv(PymeNdEncProv pymeNdEncProv) {
		this.pymeNdEncProv = pymeNdEncProv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUC_ID")
	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	@Column(name = "NDPROVD_CANTIDAD", precision = 10, scale = 0)
	public Long getNdprovdCantidad() {
		return this.ndprovdCantidad;
	}

	public void setNdprovdCantidad(Long ndprovdCantidad) {
		this.ndprovdCantidad = ndprovdCantidad;
	}

	@Column(name = "NDPROVD_DETALLE", length = 100)
	public String getNdprovdDetalle() {
		return this.ndprovdDetalle;
	}

	public void setNdprovdDetalle(String ndprovdDetalle) {
		this.ndprovdDetalle = ndprovdDetalle;
	}

	@Column(name = "NDPROVD_TOTAL_LINEA_LOCAL", precision = 18, scale = 3)
	public BigDecimal getNdprovdTotalLineaLocal() {
		return this.ndprovdTotalLineaLocal;
	}

	public void setNdprovdTotalLineaLocal(BigDecimal ndprovdTotalLineaLocal) {
		this.ndprovdTotalLineaLocal = ndprovdTotalLineaLocal;
	}

	@Column(name = "NDPROVD_TOTAL_LINEA_EXT", length = 20)
	public String getNdprovdTotalLineaExt() {
		return this.ndprovdTotalLineaExt;
	}

	public void setNdprovdTotalLineaExt(String ndprovdTotalLineaExt) {
		this.ndprovdTotalLineaExt = ndprovdTotalLineaExt;
	}

	@Column(name = "NDPROVD_CREADO_POR", length = 50)
	public String getNdprovdCreadoPor() {
		return this.ndprovdCreadoPor;
	}

	public void setNdprovdCreadoPor(String ndprovdCreadoPor) {
		this.ndprovdCreadoPor = ndprovdCreadoPor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NDPROVD_CREADO_EL", length = 7)
	public Date getNdprovdCreadoEl() {
		return this.ndprovdCreadoEl;
	}

	public void setNdprovdCreadoEl(Date ndprovdCreadoEl) {
		this.ndprovdCreadoEl = ndprovdCreadoEl;
	}

}
