package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeMsalidas generated by hbm2java
 */
public class PymeMsalidas implements java.io.Serializable {

	private long msalId;
	private PymeSubetapa pymeSubetapa;
	private String descripcion;
	private Date creadoEl;
	private String creadoPor;
	private Set<PymeDsalidas> pymeDsalidases = new HashSet<PymeDsalidas>(0);

	public PymeMsalidas() {
	}

	public PymeMsalidas(long msalId, PymeSubetapa pymeSubetapa, String descripcion) {
		this.msalId = msalId;
		this.pymeSubetapa = pymeSubetapa;
		this.descripcion = descripcion;
	}

	public PymeMsalidas(long msalId, PymeSubetapa pymeSubetapa, String descripcion, Date creadoEl, String creadoPor,
			Set<PymeDsalidas> pymeDsalidases) {
		this.msalId = msalId;
		this.pymeSubetapa = pymeSubetapa;
		this.descripcion = descripcion;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.pymeDsalidases = pymeDsalidases;
	}

	public long getMsalId() {
		return this.msalId;
	}

	public void setMsalId(long msalId) {
		this.msalId = msalId;
	}

	public PymeSubetapa getPymeSubetapa() {
		return this.pymeSubetapa;
	}

	public void setPymeSubetapa(PymeSubetapa pymeSubetapa) {
		this.pymeSubetapa = pymeSubetapa;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	public String getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

	public Set<PymeDsalidas> getPymeDsalidases() {
		return this.pymeDsalidases;
	}

	public void setPymeDsalidases(Set<PymeDsalidas> pymeDsalidases) {
		this.pymeDsalidases = pymeDsalidases;
	}

}
