package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeMlistaPrecios generated by hbm2java
 */
public class PymeMlistaPrecios implements java.io.Serializable {

	private BigDecimal mlistId;
	private PymeDtipos pymeDtipos;
	private String mlistNombre;
	private String mlistDescripcion;
	private Date mlistCreadoEl;
	private String mlistCreadoPor;
	private Set<PymeProductos> pymeProductoses = new HashSet<PymeProductos>(0);
	private Set<PymeDlistaPrecios> pymeDlistaPrecioses = new HashSet<PymeDlistaPrecios>(0);

	public PymeMlistaPrecios() {
	}

	public PymeMlistaPrecios(BigDecimal mlistId, String mlistNombre) {
		this.mlistId = mlistId;
		this.mlistNombre = mlistNombre;
	}

	public PymeMlistaPrecios(BigDecimal mlistId, PymeDtipos pymeDtipos, String mlistNombre, String mlistDescripcion,
			Date mlistCreadoEl, String mlistCreadoPor, Set<PymeProductos> pymeProductoses,
			Set<PymeDlistaPrecios> pymeDlistaPrecioses) {
		this.mlistId = mlistId;
		this.pymeDtipos = pymeDtipos;
		this.mlistNombre = mlistNombre;
		this.mlistDescripcion = mlistDescripcion;
		this.mlistCreadoEl = mlistCreadoEl;
		this.mlistCreadoPor = mlistCreadoPor;
		this.pymeProductoses = pymeProductoses;
		this.pymeDlistaPrecioses = pymeDlistaPrecioses;
	}

	public BigDecimal getMlistId() {
		return this.mlistId;
	}

	public void setMlistId(BigDecimal mlistId) {
		this.mlistId = mlistId;
	}

	public PymeDtipos getPymeDtipos() {
		return this.pymeDtipos;
	}

	public void setPymeDtipos(PymeDtipos pymeDtipos) {
		this.pymeDtipos = pymeDtipos;
	}

	public String getMlistNombre() {
		return this.mlistNombre;
	}

	public void setMlistNombre(String mlistNombre) {
		this.mlistNombre = mlistNombre;
	}

	public String getMlistDescripcion() {
		return this.mlistDescripcion;
	}

	public void setMlistDescripcion(String mlistDescripcion) {
		this.mlistDescripcion = mlistDescripcion;
	}

	public Date getMlistCreadoEl() {
		return this.mlistCreadoEl;
	}

	public void setMlistCreadoEl(Date mlistCreadoEl) {
		this.mlistCreadoEl = mlistCreadoEl;
	}

	public String getMlistCreadoPor() {
		return this.mlistCreadoPor;
	}

	public void setMlistCreadoPor(String mlistCreadoPor) {
		this.mlistCreadoPor = mlistCreadoPor;
	}

	public Set<PymeProductos> getPymeProductoses() {
		return this.pymeProductoses;
	}

	public void setPymeProductoses(Set<PymeProductos> pymeProductoses) {
		this.pymeProductoses = pymeProductoses;
	}

	public Set<PymeDlistaPrecios> getPymeDlistaPrecioses() {
		return this.pymeDlistaPrecioses;
	}

	public void setPymeDlistaPrecioses(Set<PymeDlistaPrecios> pymeDlistaPrecioses) {
		this.pymeDlistaPrecioses = pymeDlistaPrecioses;
	}

}
