package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeMentradas generated by hbm2java
 */
@Entity
@Table(name = "PYME_MENTRADAS")
public class PymeMentradas implements java.io.Serializable {

	private BigDecimal mentId;
	private PymeSubetapa pymeSubetapa;
	private Date creadoEl;
	private String creadoPor;
	private Set<PymeDentradas> pymeDentradases = new HashSet<PymeDentradas>(0);

	public PymeMentradas() {
	}

	public PymeMentradas(BigDecimal mentId, PymeSubetapa pymeSubetapa) {
		this.mentId = mentId;
		this.pymeSubetapa = pymeSubetapa;
	}

	public PymeMentradas(BigDecimal mentId, PymeSubetapa pymeSubetapa, Date creadoEl, String creadoPor,
			Set<PymeDentradas> pymeDentradases) {
		this.mentId = mentId;
		this.pymeSubetapa = pymeSubetapa;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.pymeDentradases = pymeDentradases;
	}

	@Id

	@Column(name = "MENT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMentId() {
		return this.mentId;
	}

	public void setMentId(BigDecimal mentId) {
		this.mentId = mentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBETA_ID", nullable = false)
	public PymeSubetapa getPymeSubetapa() {
		return this.pymeSubetapa;
	}

	public void setPymeSubetapa(PymeSubetapa pymeSubetapa) {
		this.pymeSubetapa = pymeSubetapa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREADO_EL", length = 7)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Column(name = "CREADO_POR", length = 200)
	public String getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeMentradas")
	public Set<PymeDentradas> getPymeDentradases() {
		return this.pymeDentradases;
	}

	public void setPymeDentradases(Set<PymeDentradas> pymeDentradases) {
		this.pymeDentradases = pymeDentradases;
	}

}
