package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeSubetapa generated by hbm2java
 */
@Entity
@Table(name = "PYME_SUBETAPA")
public class PymeSubetapa implements java.io.Serializable {

	private long subetaId;
	private PymeEtapa pymeEtapa;
	private String subetaNombre;
	private Long subetaEstado;
	private Date subetaCreadoEl;
	private String subetaCreadoPor;
	private Set<PymeMsalidas> pymeMsalidases = new HashSet<PymeMsalidas>(0);
	private Set<PymeMentradas> pymeMentradases = new HashSet<PymeMentradas>(0);

	public PymeSubetapa() {
	}

	public PymeSubetapa(long subetaId, PymeEtapa pymeEtapa, String subetaNombre) {
		this.subetaId = subetaId;
		this.pymeEtapa = pymeEtapa;
		this.subetaNombre = subetaNombre;
	}

	public PymeSubetapa(long subetaId, PymeEtapa pymeEtapa, String subetaNombre, Long subetaEstado, Date subetaCreadoEl,
			String subetaCreadoPor, Set<PymeMsalidas> pymeMsalidases, Set<PymeMentradas> pymeMentradases) {
		this.subetaId = subetaId;
		this.pymeEtapa = pymeEtapa;
		this.subetaNombre = subetaNombre;
		this.subetaEstado = subetaEstado;
		this.subetaCreadoEl = subetaCreadoEl;
		this.subetaCreadoPor = subetaCreadoPor;
		this.pymeMsalidases = pymeMsalidases;
		this.pymeMentradases = pymeMentradases;
	}

	@Id

	@Column(name = "SUBETA_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getSubetaId() {
		return this.subetaId;
	}

	public void setSubetaId(long subetaId) {
		this.subetaId = subetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETA_ID", nullable = false)
	public PymeEtapa getPymeEtapa() {
		return this.pymeEtapa;
	}

	public void setPymeEtapa(PymeEtapa pymeEtapa) {
		this.pymeEtapa = pymeEtapa;
	}

	@Column(name = "SUBETA_NOMBRE", nullable = false, length = 100)
	public String getSubetaNombre() {
		return this.subetaNombre;
	}

	public void setSubetaNombre(String subetaNombre) {
		this.subetaNombre = subetaNombre;
	}

	@Column(name = "SUBETA_ESTADO", precision = 10, scale = 0)
	public Long getSubetaEstado() {
		return this.subetaEstado;
	}

	public void setSubetaEstado(Long subetaEstado) {
		this.subetaEstado = subetaEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBETA_CREADO_EL", length = 7)
	public Date getSubetaCreadoEl() {
		return this.subetaCreadoEl;
	}

	public void setSubetaCreadoEl(Date subetaCreadoEl) {
		this.subetaCreadoEl = subetaCreadoEl;
	}

	@Column(name = "SUBETA_CREADO_POR", length = 100)
	public String getSubetaCreadoPor() {
		return this.subetaCreadoPor;
	}

	public void setSubetaCreadoPor(String subetaCreadoPor) {
		this.subetaCreadoPor = subetaCreadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeSubetapa")
	public Set<PymeMsalidas> getPymeMsalidases() {
		return this.pymeMsalidases;
	}

	public void setPymeMsalidases(Set<PymeMsalidas> pymeMsalidases) {
		this.pymeMsalidases = pymeMsalidases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeSubetapa")
	public Set<PymeMentradas> getPymeMentradases() {
		return this.pymeMentradases;
	}

	public void setPymeMentradases(Set<PymeMentradas> pymeMentradases) {
		this.pymeMentradases = pymeMentradases;
	}

}
