package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeMsalidas generated by hbm2java
 */
@Entity
@Table(name = "PYME_MSALIDAS")
public class PymeMsalidas implements java.io.Serializable {

	private long msalId;
	private PymeSubetapa pymeSubetapa;
	private String descripcion;
	private Date creadoEl;
	private String creadoPor;
	private Set<PymeDsalidas> pymeDsalidases = new HashSet<PymeDsalidas>(0);

	public PymeMsalidas() {
	}

	public PymeMsalidas(long msalId, PymeSubetapa pymeSubetapa, String descripcion) {
		this.msalId = msalId;
		this.pymeSubetapa = pymeSubetapa;
		this.descripcion = descripcion;
	}

	public PymeMsalidas(long msalId, PymeSubetapa pymeSubetapa, String descripcion, Date creadoEl, String creadoPor,
			Set<PymeDsalidas> pymeDsalidases) {
		this.msalId = msalId;
		this.pymeSubetapa = pymeSubetapa;
		this.descripcion = descripcion;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.pymeDsalidases = pymeDsalidases;
	}

	@Id

	@Column(name = "MSAL_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public long getMsalId() {
		return this.msalId;
	}

	public void setMsalId(long msalId) {
		this.msalId = msalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBETA_ID", nullable = false)
	public PymeSubetapa getPymeSubetapa() {
		return this.pymeSubetapa;
	}

	public void setPymeSubetapa(PymeSubetapa pymeSubetapa) {
		this.pymeSubetapa = pymeSubetapa;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREADO_EL", length = 7)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Column(name = "CREADO_POR", length = 50)
	public String getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeMsalidas")
	public Set<PymeDsalidas> getPymeDsalidases() {
		return this.pymeDsalidases;
	}

	public void setPymeDsalidases(Set<PymeDsalidas> pymeDsalidases) {
		this.pymeDsalidases = pymeDsalidases;
	}

}
