package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PymeDlistaPrecios generated by hbm2java
 */
@Entity
@Table(name = "PYME_DLISTA_PRECIOS", uniqueConstraints = @UniqueConstraint(columnNames = { "MLISTA_ID", "PRODUC_ID" }))
public class PymeDlistaPrecios implements java.io.Serializable {

	private long dlistaId;
	private PymeMlistaPrecios pymeMlistaPrecios;
	private long producId;
	private BigDecimal dlistaPrecio;

	public PymeDlistaPrecios() {
	}

	public PymeDlistaPrecios(long dlistaId, PymeMlistaPrecios pymeMlistaPrecios, long producId,
			BigDecimal dlistaPrecio) {
		this.dlistaId = dlistaId;
		this.pymeMlistaPrecios = pymeMlistaPrecios;
		this.producId = producId;
		this.dlistaPrecio = dlistaPrecio;
	}

	@Id

	@Column(name = "DLISTA_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDlistaId() {
		return this.dlistaId;
	}

	public void setDlistaId(long dlistaId) {
		this.dlistaId = dlistaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLISTA_ID", nullable = false)
	public PymeMlistaPrecios getPymeMlistaPrecios() {
		return this.pymeMlistaPrecios;
	}

	public void setPymeMlistaPrecios(PymeMlistaPrecios pymeMlistaPrecios) {
		this.pymeMlistaPrecios = pymeMlistaPrecios;
	}

	@Column(name = "PRODUC_ID", nullable = false, precision = 10, scale = 0)
	public long getProducId() {
		return this.producId;
	}

	public void setProducId(long producId) {
		this.producId = producId;
	}

	@Column(name = "DLISTA_PRECIO", nullable = false, precision = 18)
	public BigDecimal getDlistaPrecio() {
		return this.dlistaPrecio;
	}

	public void setDlistaPrecio(BigDecimal dlistaPrecio) {
		this.dlistaPrecio = dlistaPrecio;
	}

}
