package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PymeNdDetProv generated by hbm2java
 */
public class PymeNdDetProv implements java.io.Serializable {

	private long ndprovdId;
	private PymeNdEncProv pymeNdEncProv;
	private PymeProductos pymeProductos;
	private Long ndprovdCantidad;
	private String ndprovdDetalle;
	private BigDecimal ndprovdTotalLineaLocal;
	private String ndprovdTotalLineaExt;
	private String ndprovdCreadoPor;
	private Date ndprovdCreadoEl;

	public PymeNdDetProv() {
	}

	public PymeNdDetProv(long ndprovdId, PymeNdEncProv pymeNdEncProv) {
		this.ndprovdId = ndprovdId;
		this.pymeNdEncProv = pymeNdEncProv;
	}

	public PymeNdDetProv(long ndprovdId, PymeNdEncProv pymeNdEncProv, PymeProductos pymeProductos, Long ndprovdCantidad,
			String ndprovdDetalle, BigDecimal ndprovdTotalLineaLocal, String ndprovdTotalLineaExt,
			String ndprovdCreadoPor, Date ndprovdCreadoEl) {
		this.ndprovdId = ndprovdId;
		this.pymeNdEncProv = pymeNdEncProv;
		this.pymeProductos = pymeProductos;
		this.ndprovdCantidad = ndprovdCantidad;
		this.ndprovdDetalle = ndprovdDetalle;
		this.ndprovdTotalLineaLocal = ndprovdTotalLineaLocal;
		this.ndprovdTotalLineaExt = ndprovdTotalLineaExt;
		this.ndprovdCreadoPor = ndprovdCreadoPor;
		this.ndprovdCreadoEl = ndprovdCreadoEl;
	}

	public long getNdprovdId() {
		return this.ndprovdId;
	}

	public void setNdprovdId(long ndprovdId) {
		this.ndprovdId = ndprovdId;
	}

	public PymeNdEncProv getPymeNdEncProv() {
		return this.pymeNdEncProv;
	}

	public void setPymeNdEncProv(PymeNdEncProv pymeNdEncProv) {
		this.pymeNdEncProv = pymeNdEncProv;
	}

	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	public Long getNdprovdCantidad() {
		return this.ndprovdCantidad;
	}

	public void setNdprovdCantidad(Long ndprovdCantidad) {
		this.ndprovdCantidad = ndprovdCantidad;
	}

	public String getNdprovdDetalle() {
		return this.ndprovdDetalle;
	}

	public void setNdprovdDetalle(String ndprovdDetalle) {
		this.ndprovdDetalle = ndprovdDetalle;
	}

	public BigDecimal getNdprovdTotalLineaLocal() {
		return this.ndprovdTotalLineaLocal;
	}

	public void setNdprovdTotalLineaLocal(BigDecimal ndprovdTotalLineaLocal) {
		this.ndprovdTotalLineaLocal = ndprovdTotalLineaLocal;
	}

	public String getNdprovdTotalLineaExt() {
		return this.ndprovdTotalLineaExt;
	}

	public void setNdprovdTotalLineaExt(String ndprovdTotalLineaExt) {
		this.ndprovdTotalLineaExt = ndprovdTotalLineaExt;
	}

	public String getNdprovdCreadoPor() {
		return this.ndprovdCreadoPor;
	}

	public void setNdprovdCreadoPor(String ndprovdCreadoPor) {
		this.ndprovdCreadoPor = ndprovdCreadoPor;
	}

	public Date getNdprovdCreadoEl() {
		return this.ndprovdCreadoEl;
	}

	public void setNdprovdCreadoEl(Date ndprovdCreadoEl) {
		this.ndprovdCreadoEl = ndprovdCreadoEl;
	}

}
