package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeDsalidas generated by hbm2java
 */
@Entity
@Table(name = "PYME_DSALIDAS")
public class PymeDsalidas implements java.io.Serializable {

	private long dsalId;
	private PymeProductos pymeProductos;
	private PymeDtipos pymeDtiposByDsalTipoMov;
	private PymeMsalidas pymeMsalidas;
	private PymeDtipos pymeDtiposByDsalEstadoDoc;
	private long dsalCantidad;
	private Date dsalFechaSalida;
	private String dsalCreadoPor;
	private String dsalAutorizadoPor;

	public PymeDsalidas() {
	}

	public PymeDsalidas(long dsalId, PymeProductos pymeProductos, PymeDtipos pymeDtiposByDsalTipoMov,
			PymeMsalidas pymeMsalidas, long dsalCantidad) {
		this.dsalId = dsalId;
		this.pymeProductos = pymeProductos;
		this.pymeDtiposByDsalTipoMov = pymeDtiposByDsalTipoMov;
		this.pymeMsalidas = pymeMsalidas;
		this.dsalCantidad = dsalCantidad;
	}

	public PymeDsalidas(long dsalId, PymeProductos pymeProductos, PymeDtipos pymeDtiposByDsalTipoMov,
			PymeMsalidas pymeMsalidas, PymeDtipos pymeDtiposByDsalEstadoDoc, long dsalCantidad, Date dsalFechaSalida,
			String dsalCreadoPor, String dsalAutorizadoPor) {
		this.dsalId = dsalId;
		this.pymeProductos = pymeProductos;
		this.pymeDtiposByDsalTipoMov = pymeDtiposByDsalTipoMov;
		this.pymeMsalidas = pymeMsalidas;
		this.pymeDtiposByDsalEstadoDoc = pymeDtiposByDsalEstadoDoc;
		this.dsalCantidad = dsalCantidad;
		this.dsalFechaSalida = dsalFechaSalida;
		this.dsalCreadoPor = dsalCreadoPor;
		this.dsalAutorizadoPor = dsalAutorizadoPor;
	}

	@Id

	@Column(name = "DSAL_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDsalId() {
		return this.dsalId;
	}

	public void setDsalId(long dsalId) {
		this.dsalId = dsalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUC_ID", nullable = false)
	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DSAL_TIPO_MOV", nullable = false)
	public PymeDtipos getPymeDtiposByDsalTipoMov() {
		return this.pymeDtiposByDsalTipoMov;
	}

	public void setPymeDtiposByDsalTipoMov(PymeDtipos pymeDtiposByDsalTipoMov) {
		this.pymeDtiposByDsalTipoMov = pymeDtiposByDsalTipoMov;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSAL_ID", nullable = false)
	public PymeMsalidas getPymeMsalidas() {
		return this.pymeMsalidas;
	}

	public void setPymeMsalidas(PymeMsalidas pymeMsalidas) {
		this.pymeMsalidas = pymeMsalidas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DSAL_ESTADO_DOC")
	public PymeDtipos getPymeDtiposByDsalEstadoDoc() {
		return this.pymeDtiposByDsalEstadoDoc;
	}

	public void setPymeDtiposByDsalEstadoDoc(PymeDtipos pymeDtiposByDsalEstadoDoc) {
		this.pymeDtiposByDsalEstadoDoc = pymeDtiposByDsalEstadoDoc;
	}

	@Column(name = "DSAL_CANTIDAD", nullable = false, precision = 10, scale = 0)
	public long getDsalCantidad() {
		return this.dsalCantidad;
	}

	public void setDsalCantidad(long dsalCantidad) {
		this.dsalCantidad = dsalCantidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DSAL_FECHA_SALIDA", length = 7)
	public Date getDsalFechaSalida() {
		return this.dsalFechaSalida;
	}

	public void setDsalFechaSalida(Date dsalFechaSalida) {
		this.dsalFechaSalida = dsalFechaSalida;
	}

	@Column(name = "DSAL_CREADO_POR", length = 50)
	public String getDsalCreadoPor() {
		return this.dsalCreadoPor;
	}

	public void setDsalCreadoPor(String dsalCreadoPor) {
		this.dsalCreadoPor = dsalCreadoPor;
	}

	@Column(name = "DSAL_AUTORIZADO_POR", length = 50)
	public String getDsalAutorizadoPor() {
		return this.dsalAutorizadoPor;
	}

	public void setDsalAutorizadoPor(String dsalAutorizadoPor) {
		this.dsalAutorizadoPor = dsalAutorizadoPor;
	}

}
