package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PymeMtipos generated by hbm2java
 */
@Entity
@Table(name = "PYME_MTIPOS", uniqueConstraints = @UniqueConstraint(columnNames = "MTIPO_NOMBRE"))
public class PymeMtipos implements java.io.Serializable {

	private long mtipoId;
	private String mtipoNombre;
	private Date mtipoCreadoEl;
	private Set<PymeDtipos> pymeDtiposes = new HashSet<PymeDtipos>(0);

	public PymeMtipos() {
	}

	public PymeMtipos(long mtipoId, String mtipoNombre, Date mtipoCreadoEl) {
		this.mtipoId = mtipoId;
		this.mtipoNombre = mtipoNombre;
		this.mtipoCreadoEl = mtipoCreadoEl;
	}

	public PymeMtipos(long mtipoId, String mtipoNombre, Date mtipoCreadoEl, Set<PymeDtipos> pymeDtiposes) {
		this.mtipoId = mtipoId;
		this.mtipoNombre = mtipoNombre;
		this.mtipoCreadoEl = mtipoCreadoEl;
		this.pymeDtiposes = pymeDtiposes;
	}

	@Id

	@Column(name = "MTIPO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getMtipoId() {
		return this.mtipoId;
	}

	public void setMtipoId(long mtipoId) {
		this.mtipoId = mtipoId;
	}

	@Column(name = "MTIPO_NOMBRE", unique = true, nullable = false, length = 50)
	public String getMtipoNombre() {
		return this.mtipoNombre;
	}

	public void setMtipoNombre(String mtipoNombre) {
		this.mtipoNombre = mtipoNombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MTIPO_CREADO_EL", nullable = false, length = 7)
	public Date getMtipoCreadoEl() {
		return this.mtipoCreadoEl;
	}

	public void setMtipoCreadoEl(Date mtipoCreadoEl) {
		this.mtipoCreadoEl = mtipoCreadoEl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeMtipos")
	public Set<PymeDtipos> getPymeDtiposes() {
		return this.pymeDtiposes;
	}

	public void setPymeDtiposes(Set<PymeDtipos> pymeDtiposes) {
		this.pymeDtiposes = pymeDtiposes;
	}

}
