package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeSubetapa generated by hbm2java
 */
public class PymeSubetapa implements java.io.Serializable {

	private long subetaId;
	private PymeDtipos pymeDtipos;
	private PymeEtapa pymeEtapa;
	private String subetaNombre;
	private Date subetaCreadoEl;
	private String subetaCreadoPor;
	private Set<PymeMsalidas> pymeMsalidases = new HashSet<PymeMsalidas>(0);
	private Set<PymeMentradas> pymeMentradases = new HashSet<PymeMentradas>(0);

	public PymeSubetapa() {
	}

	public PymeSubetapa(long subetaId, PymeEtapa pymeEtapa, String subetaNombre) {
		this.subetaId = subetaId;
		this.pymeEtapa = pymeEtapa;
		this.subetaNombre = subetaNombre;
	}

	public PymeSubetapa(long subetaId, PymeDtipos pymeDtipos, PymeEtapa pymeEtapa, String subetaNombre,
			Date subetaCreadoEl, String subetaCreadoPor, Set<PymeMsalidas> pymeMsalidases,
			Set<PymeMentradas> pymeMentradases) {
		this.subetaId = subetaId;
		this.pymeDtipos = pymeDtipos;
		this.pymeEtapa = pymeEtapa;
		this.subetaNombre = subetaNombre;
		this.subetaCreadoEl = subetaCreadoEl;
		this.subetaCreadoPor = subetaCreadoPor;
		this.pymeMsalidases = pymeMsalidases;
		this.pymeMentradases = pymeMentradases;
	}

	public long getSubetaId() {
		return this.subetaId;
	}

	public void setSubetaId(long subetaId) {
		this.subetaId = subetaId;
	}

	public PymeDtipos getPymeDtipos() {
		return this.pymeDtipos;
	}

	public void setPymeDtipos(PymeDtipos pymeDtipos) {
		this.pymeDtipos = pymeDtipos;
	}

	public PymeEtapa getPymeEtapa() {
		return this.pymeEtapa;
	}

	public void setPymeEtapa(PymeEtapa pymeEtapa) {
		this.pymeEtapa = pymeEtapa;
	}

	public String getSubetaNombre() {
		return this.subetaNombre;
	}

	public void setSubetaNombre(String subetaNombre) {
		this.subetaNombre = subetaNombre;
	}

	public Date getSubetaCreadoEl() {
		return this.subetaCreadoEl;
	}

	public void setSubetaCreadoEl(Date subetaCreadoEl) {
		this.subetaCreadoEl = subetaCreadoEl;
	}

	public String getSubetaCreadoPor() {
		return this.subetaCreadoPor;
	}

	public void setSubetaCreadoPor(String subetaCreadoPor) {
		this.subetaCreadoPor = subetaCreadoPor;
	}

	public Set<PymeMsalidas> getPymeMsalidases() {
		return this.pymeMsalidases;
	}

	public void setPymeMsalidases(Set<PymeMsalidas> pymeMsalidases) {
		this.pymeMsalidases = pymeMsalidases;
	}

	public Set<PymeMentradas> getPymeMentradases() {
		return this.pymeMentradases;
	}

	public void setPymeMentradases(Set<PymeMentradas> pymeMentradases) {
		this.pymeMentradases = pymeMentradases;
	}

}
