package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeProductos generated by hbm2java
 */
@Entity
@Table(name = "PYME_PRODUCTOS")
public class PymeProductos implements java.io.Serializable {

	private long producId;
	private PymeMlistaPrecios pymeMlistaPrecios;
	private String producIdAlterno;
	private String producDescripcion;
	private long etaId;
	private long producEstado;
	private Long producMedida;
	private BigDecimal producPeso;
	private Long producTipo;
	private long producExistencia;
	private Long producReservado;
	private Long producDisponible;
	private Date producCreadoEl;
	private String producCreadoPor;
	private Set<PymeDentradas> pymeDentradases = new HashSet<PymeDentradas>(0);
	private Set<PymeFacncDetProv> pymeFacncDetProvs = new HashSet<PymeFacncDetProv>(0);
	private Set<PymeDsalidas> pymeDsalidases = new HashSet<PymeDsalidas>(0);
	private Set<PymeFacncDetCli> pymeFacncDetClis = new HashSet<PymeFacncDetCli>(0);
	private Set<PymeNdDetCli> pymeNdDetClis = new HashSet<PymeNdDetCli>(0);
	private Set<PymeNdDetProv> pymeNdDetProvs = new HashSet<PymeNdDetProv>(0);

	public PymeProductos() {
	}

	public PymeProductos(long producId, PymeMlistaPrecios pymeMlistaPrecios, String producIdAlterno,
			String producDescripcion, long etaId, long producEstado, long producExistencia) {
		this.producId = producId;
		this.pymeMlistaPrecios = pymeMlistaPrecios;
		this.producIdAlterno = producIdAlterno;
		this.producDescripcion = producDescripcion;
		this.etaId = etaId;
		this.producEstado = producEstado;
		this.producExistencia = producExistencia;
	}

	public PymeProductos(long producId, PymeMlistaPrecios pymeMlistaPrecios, String producIdAlterno,
			String producDescripcion, long etaId, long producEstado, Long producMedida, BigDecimal producPeso,
			Long producTipo, long producExistencia, Long producReservado, Long producDisponible, Date producCreadoEl,
			String producCreadoPor, Set<PymeDentradas> pymeDentradases, Set<PymeFacncDetProv> pymeFacncDetProvs,
			Set<PymeDsalidas> pymeDsalidases, Set<PymeFacncDetCli> pymeFacncDetClis, Set<PymeNdDetCli> pymeNdDetClis,
			Set<PymeNdDetProv> pymeNdDetProvs) {
		this.producId = producId;
		this.pymeMlistaPrecios = pymeMlistaPrecios;
		this.producIdAlterno = producIdAlterno;
		this.producDescripcion = producDescripcion;
		this.etaId = etaId;
		this.producEstado = producEstado;
		this.producMedida = producMedida;
		this.producPeso = producPeso;
		this.producTipo = producTipo;
		this.producExistencia = producExistencia;
		this.producReservado = producReservado;
		this.producDisponible = producDisponible;
		this.producCreadoEl = producCreadoEl;
		this.producCreadoPor = producCreadoPor;
		this.pymeDentradases = pymeDentradases;
		this.pymeFacncDetProvs = pymeFacncDetProvs;
		this.pymeDsalidases = pymeDsalidases;
		this.pymeFacncDetClis = pymeFacncDetClis;
		this.pymeNdDetClis = pymeNdDetClis;
		this.pymeNdDetProvs = pymeNdDetProvs;
	}

	@Id

	@Column(name = "PRODUC_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public long getProducId() {
		return this.producId;
	}

	public void setProducId(long producId) {
		this.producId = producId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLIST_ID", nullable = false)
	public PymeMlistaPrecios getPymeMlistaPrecios() {
		return this.pymeMlistaPrecios;
	}

	public void setPymeMlistaPrecios(PymeMlistaPrecios pymeMlistaPrecios) {
		this.pymeMlistaPrecios = pymeMlistaPrecios;
	}

	@Column(name = "PRODUC_ID_ALTERNO", nullable = false, length = 200)
	public String getProducIdAlterno() {
		return this.producIdAlterno;
	}

	public void setProducIdAlterno(String producIdAlterno) {
		this.producIdAlterno = producIdAlterno;
	}

	@Column(name = "PRODUC_DESCRIPCION", nullable = false, length = 200)
	public String getProducDescripcion() {
		return this.producDescripcion;
	}

	public void setProducDescripcion(String producDescripcion) {
		this.producDescripcion = producDescripcion;
	}

	@Column(name = "ETA_ID", nullable = false, precision = 10, scale = 0)
	public long getEtaId() {
		return this.etaId;
	}

	public void setEtaId(long etaId) {
		this.etaId = etaId;
	}

	@Column(name = "PRODUC_ESTADO", nullable = false, precision = 10, scale = 0)
	public long getProducEstado() {
		return this.producEstado;
	}

	public void setProducEstado(long producEstado) {
		this.producEstado = producEstado;
	}

	@Column(name = "PRODUC_MEDIDA", precision = 10, scale = 0)
	public Long getProducMedida() {
		return this.producMedida;
	}

	public void setProducMedida(Long producMedida) {
		this.producMedida = producMedida;
	}

	@Column(name = "PRODUC_PESO", precision = 18, scale = 3)
	public BigDecimal getProducPeso() {
		return this.producPeso;
	}

	public void setProducPeso(BigDecimal producPeso) {
		this.producPeso = producPeso;
	}

	@Column(name = "PRODUC_TIPO", precision = 10, scale = 0)
	public Long getProducTipo() {
		return this.producTipo;
	}

	public void setProducTipo(Long producTipo) {
		this.producTipo = producTipo;
	}

	@Column(name = "PRODUC_EXISTENCIA", nullable = false, precision = 18, scale = 0)
	public long getProducExistencia() {
		return this.producExistencia;
	}

	public void setProducExistencia(long producExistencia) {
		this.producExistencia = producExistencia;
	}

	@Column(name = "PRODUC_RESERVADO", precision = 18, scale = 0)
	public Long getProducReservado() {
		return this.producReservado;
	}

	public void setProducReservado(Long producReservado) {
		this.producReservado = producReservado;
	}

	@Column(name = "PRODUC_DISPONIBLE", precision = 18, scale = 0)
	public Long getProducDisponible() {
		return this.producDisponible;
	}

	public void setProducDisponible(Long producDisponible) {
		this.producDisponible = producDisponible;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRODUC_CREADO_EL", length = 7)
	public Date getProducCreadoEl() {
		return this.producCreadoEl;
	}

	public void setProducCreadoEl(Date producCreadoEl) {
		this.producCreadoEl = producCreadoEl;
	}

	@Column(name = "PRODUC_CREADO_POR", length = 50)
	public String getProducCreadoPor() {
		return this.producCreadoPor;
	}

	public void setProducCreadoPor(String producCreadoPor) {
		this.producCreadoPor = producCreadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProductos")
	public Set<PymeDentradas> getPymeDentradases() {
		return this.pymeDentradases;
	}

	public void setPymeDentradases(Set<PymeDentradas> pymeDentradases) {
		this.pymeDentradases = pymeDentradases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProductos")
	public Set<PymeFacncDetProv> getPymeFacncDetProvs() {
		return this.pymeFacncDetProvs;
	}

	public void setPymeFacncDetProvs(Set<PymeFacncDetProv> pymeFacncDetProvs) {
		this.pymeFacncDetProvs = pymeFacncDetProvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProductos")
	public Set<PymeDsalidas> getPymeDsalidases() {
		return this.pymeDsalidases;
	}

	public void setPymeDsalidases(Set<PymeDsalidas> pymeDsalidases) {
		this.pymeDsalidases = pymeDsalidases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProductos")
	public Set<PymeFacncDetCli> getPymeFacncDetClis() {
		return this.pymeFacncDetClis;
	}

	public void setPymeFacncDetClis(Set<PymeFacncDetCli> pymeFacncDetClis) {
		this.pymeFacncDetClis = pymeFacncDetClis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProductos")
	public Set<PymeNdDetCli> getPymeNdDetClis() {
		return this.pymeNdDetClis;
	}

	public void setPymeNdDetClis(Set<PymeNdDetCli> pymeNdDetClis) {
		this.pymeNdDetClis = pymeNdDetClis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProductos")
	public Set<PymeNdDetProv> getPymeNdDetProvs() {
		return this.pymeNdDetProvs;
	}

	public void setPymeNdDetProvs(Set<PymeNdDetProv> pymeNdDetProvs) {
		this.pymeNdDetProvs = pymeNdDetProvs;
	}

}
