package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeDsalidas generated by hbm2java
 */
@Entity
@Table(name = "PYME_DSALIDAS")
public class PymeDsalidas implements java.io.Serializable {

	private long dsalId;
	private PymeProductos pymeProductos;
	private PymeMsalidas pymeMsalidas;
	private long dsalTipoMov;
	private long dsalCantidad;
	private Date dsalFechaSalida;
	private Long dsalEstadoDoc;
	private String dsalCreadoPor;
	private String dsalAutorizadoPor;

	public PymeDsalidas() {
	}

	public PymeDsalidas(long dsalId, PymeProductos pymeProductos, PymeMsalidas pymeMsalidas, long dsalTipoMov,
			long dsalCantidad) {
		this.dsalId = dsalId;
		this.pymeProductos = pymeProductos;
		this.pymeMsalidas = pymeMsalidas;
		this.dsalTipoMov = dsalTipoMov;
		this.dsalCantidad = dsalCantidad;
	}

	public PymeDsalidas(long dsalId, PymeProductos pymeProductos, PymeMsalidas pymeMsalidas, long dsalTipoMov,
			long dsalCantidad, Date dsalFechaSalida, Long dsalEstadoDoc, String dsalCreadoPor,
			String dsalAutorizadoPor) {
		this.dsalId = dsalId;
		this.pymeProductos = pymeProductos;
		this.pymeMsalidas = pymeMsalidas;
		this.dsalTipoMov = dsalTipoMov;
		this.dsalCantidad = dsalCantidad;
		this.dsalFechaSalida = dsalFechaSalida;
		this.dsalEstadoDoc = dsalEstadoDoc;
		this.dsalCreadoPor = dsalCreadoPor;
		this.dsalAutorizadoPor = dsalAutorizadoPor;
	}

	@Id

	@Column(name = "DSAL_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDsalId() {
		return this.dsalId;
	}

	public void setDsalId(long dsalId) {
		this.dsalId = dsalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUC_ID", nullable = false)
	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSAL_ID", nullable = false)
	public PymeMsalidas getPymeMsalidas() {
		return this.pymeMsalidas;
	}

	public void setPymeMsalidas(PymeMsalidas pymeMsalidas) {
		this.pymeMsalidas = pymeMsalidas;
	}

	@Column(name = "DSAL_TIPO_MOV", nullable = false, precision = 10, scale = 0)
	public long getDsalTipoMov() {
		return this.dsalTipoMov;
	}

	public void setDsalTipoMov(long dsalTipoMov) {
		this.dsalTipoMov = dsalTipoMov;
	}

	@Column(name = "DSAL_CANTIDAD", nullable = false, precision = 10, scale = 0)
	public long getDsalCantidad() {
		return this.dsalCantidad;
	}

	public void setDsalCantidad(long dsalCantidad) {
		this.dsalCantidad = dsalCantidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DSAL_FECHA_SALIDA", length = 7)
	public Date getDsalFechaSalida() {
		return this.dsalFechaSalida;
	}

	public void setDsalFechaSalida(Date dsalFechaSalida) {
		this.dsalFechaSalida = dsalFechaSalida;
	}

	@Column(name = "DSAL_ESTADO_DOC", precision = 10, scale = 0)
	public Long getDsalEstadoDoc() {
		return this.dsalEstadoDoc;
	}

	public void setDsalEstadoDoc(Long dsalEstadoDoc) {
		this.dsalEstadoDoc = dsalEstadoDoc;
	}

	@Column(name = "DSAL_CREADO_POR", length = 50)
	public String getDsalCreadoPor() {
		return this.dsalCreadoPor;
	}

	public void setDsalCreadoPor(String dsalCreadoPor) {
		this.dsalCreadoPor = dsalCreadoPor;
	}

	@Column(name = "DSAL_AUTORIZADO_POR", length = 50)
	public String getDsalAutorizadoPor() {
		return this.dsalAutorizadoPor;
	}

	public void setDsalAutorizadoPor(String dsalAutorizadoPor) {
		this.dsalAutorizadoPor = dsalAutorizadoPor;
	}

}
