package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PymeDentradas generated by hbm2java
 */
public class PymeDentradas implements java.io.Serializable {

	private long dentId;
	private PymeProductos pymeProductos;
	private PymeMentradas pymeMentradas;
	private long dentCantidad;
	private BigDecimal dentPrecioUnitario;
	private Long provId;
	private String dentDetalle;
	private Date dentCreadoEl;
	private String dentCreadoPor;

	public PymeDentradas() {
	}

	public PymeDentradas(long dentId, PymeProductos pymeProductos, PymeMentradas pymeMentradas, long dentCantidad,
			BigDecimal dentPrecioUnitario) {
		this.dentId = dentId;
		this.pymeProductos = pymeProductos;
		this.pymeMentradas = pymeMentradas;
		this.dentCantidad = dentCantidad;
		this.dentPrecioUnitario = dentPrecioUnitario;
	}

	public PymeDentradas(long dentId, PymeProductos pymeProductos, PymeMentradas pymeMentradas, long dentCantidad,
			BigDecimal dentPrecioUnitario, Long provId, String dentDetalle, Date dentCreadoEl, String dentCreadoPor) {
		this.dentId = dentId;
		this.pymeProductos = pymeProductos;
		this.pymeMentradas = pymeMentradas;
		this.dentCantidad = dentCantidad;
		this.dentPrecioUnitario = dentPrecioUnitario;
		this.provId = provId;
		this.dentDetalle = dentDetalle;
		this.dentCreadoEl = dentCreadoEl;
		this.dentCreadoPor = dentCreadoPor;
	}

	public long getDentId() {
		return this.dentId;
	}

	public void setDentId(long dentId) {
		this.dentId = dentId;
	}

	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	public PymeMentradas getPymeMentradas() {
		return this.pymeMentradas;
	}

	public void setPymeMentradas(PymeMentradas pymeMentradas) {
		this.pymeMentradas = pymeMentradas;
	}

	public long getDentCantidad() {
		return this.dentCantidad;
	}

	public void setDentCantidad(long dentCantidad) {
		this.dentCantidad = dentCantidad;
	}

	public BigDecimal getDentPrecioUnitario() {
		return this.dentPrecioUnitario;
	}

	public void setDentPrecioUnitario(BigDecimal dentPrecioUnitario) {
		this.dentPrecioUnitario = dentPrecioUnitario;
	}

	public Long getProvId() {
		return this.provId;
	}

	public void setProvId(Long provId) {
		this.provId = provId;
	}

	public String getDentDetalle() {
		return this.dentDetalle;
	}

	public void setDentDetalle(String dentDetalle) {
		this.dentDetalle = dentDetalle;
	}

	public Date getDentCreadoEl() {
		return this.dentCreadoEl;
	}

	public void setDentCreadoEl(Date dentCreadoEl) {
		this.dentCreadoEl = dentCreadoEl;
	}

	public String getDentCreadoPor() {
		return this.dentCreadoPor;
	}

	public void setDentCreadoPor(String dentCreadoPor) {
		this.dentCreadoPor = dentCreadoPor;
	}

}
