package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeProyecto generated by hbm2java
 */
public class PymeProyecto implements java.io.Serializable {

	private long proyId;
	private PymeEmpresa pymeEmpresa;
	private PymeDtipos pymeDtipos;
	private String proyNombre;
	private String proyDescripcion;
	private String proyCreadoPor;
	private Date proyCreadoEl;
	private Set<PymeSysSeguridad> pymeSysSeguridads = new HashSet<PymeSysSeguridad>(0);
	private Set<PymeFacncEncCli> pymeFacncEncClis = new HashSet<PymeFacncEncCli>(0);
	private Set<PymeEtapa> pymeEtapas = new HashSet<PymeEtapa>(0);

	public PymeProyecto() {
	}

	public PymeProyecto(long proyId, PymeEmpresa pymeEmpresa, PymeDtipos pymeDtipos, String proyNombre,
			String proyDescripcion, String proyCreadoPor, Date proyCreadoEl) {
		this.proyId = proyId;
		this.pymeEmpresa = pymeEmpresa;
		this.pymeDtipos = pymeDtipos;
		this.proyNombre = proyNombre;
		this.proyDescripcion = proyDescripcion;
		this.proyCreadoPor = proyCreadoPor;
		this.proyCreadoEl = proyCreadoEl;
	}

	public PymeProyecto(long proyId, PymeEmpresa pymeEmpresa, PymeDtipos pymeDtipos, String proyNombre,
			String proyDescripcion, String proyCreadoPor, Date proyCreadoEl, Set<PymeSysSeguridad> pymeSysSeguridads,
			Set<PymeFacncEncCli> pymeFacncEncClis, Set<PymeEtapa> pymeEtapas) {
		this.proyId = proyId;
		this.pymeEmpresa = pymeEmpresa;
		this.pymeDtipos = pymeDtipos;
		this.proyNombre = proyNombre;
		this.proyDescripcion = proyDescripcion;
		this.proyCreadoPor = proyCreadoPor;
		this.proyCreadoEl = proyCreadoEl;
		this.pymeSysSeguridads = pymeSysSeguridads;
		this.pymeFacncEncClis = pymeFacncEncClis;
		this.pymeEtapas = pymeEtapas;
	}

	public long getProyId() {
		return this.proyId;
	}

	public void setProyId(long proyId) {
		this.proyId = proyId;
	}

	public PymeEmpresa getPymeEmpresa() {
		return this.pymeEmpresa;
	}

	public void setPymeEmpresa(PymeEmpresa pymeEmpresa) {
		this.pymeEmpresa = pymeEmpresa;
	}

	public PymeDtipos getPymeDtipos() {
		return this.pymeDtipos;
	}

	public void setPymeDtipos(PymeDtipos pymeDtipos) {
		this.pymeDtipos = pymeDtipos;
	}

	public String getProyNombre() {
		return this.proyNombre;
	}

	public void setProyNombre(String proyNombre) {
		this.proyNombre = proyNombre;
	}

	public String getProyDescripcion() {
		return this.proyDescripcion;
	}

	public void setProyDescripcion(String proyDescripcion) {
		this.proyDescripcion = proyDescripcion;
	}

	public String getProyCreadoPor() {
		return this.proyCreadoPor;
	}

	public void setProyCreadoPor(String proyCreadoPor) {
		this.proyCreadoPor = proyCreadoPor;
	}

	public Date getProyCreadoEl() {
		return this.proyCreadoEl;
	}

	public void setProyCreadoEl(Date proyCreadoEl) {
		this.proyCreadoEl = proyCreadoEl;
	}

	public Set<PymeSysSeguridad> getPymeSysSeguridads() {
		return this.pymeSysSeguridads;
	}

	public void setPymeSysSeguridads(Set<PymeSysSeguridad> pymeSysSeguridads) {
		this.pymeSysSeguridads = pymeSysSeguridads;
	}

	public Set<PymeFacncEncCli> getPymeFacncEncClis() {
		return this.pymeFacncEncClis;
	}

	public void setPymeFacncEncClis(Set<PymeFacncEncCli> pymeFacncEncClis) {
		this.pymeFacncEncClis = pymeFacncEncClis;
	}

	public Set<PymeEtapa> getPymeEtapas() {
		return this.pymeEtapas;
	}

	public void setPymeEtapas(Set<PymeEtapa> pymeEtapas) {
		this.pymeEtapas = pymeEtapas;
	}

}
