package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PymeMtipos generated by hbm2java
 */
@Entity
@Table(name = "PYME_MTIPOS", uniqueConstraints = @UniqueConstraint(columnNames = "MTIPO_NOMBRE"))
public class PymeMtipos implements java.io.Serializable {

	private long mtipoId;
	private String mtipoNombre;
	private Date mtipoCreadoEl;

	public PymeMtipos() {
	}

	public PymeMtipos(long mtipoId, String mtipoNombre, Date mtipoCreadoEl) {
		this.mtipoId = mtipoId;
		this.mtipoNombre = mtipoNombre;
		this.mtipoCreadoEl = mtipoCreadoEl;
	}

	@Id

	@Column(name = "MTIPO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getMtipoId() {
		return this.mtipoId;
	}

	public void setMtipoId(long mtipoId) {
		this.mtipoId = mtipoId;
	}

	@Column(name = "MTIPO_NOMBRE", unique = true, nullable = false, length = 50)
	public String getMtipoNombre() {
		return this.mtipoNombre;
	}

	public void setMtipoNombre(String mtipoNombre) {
		this.mtipoNombre = mtipoNombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MTIPO_CREADO_EL", nullable = false, length = 7)
	public Date getMtipoCreadoEl() {
		return this.mtipoCreadoEl;
	}

	public void setMtipoCreadoEl(Date mtipoCreadoEl) {
		this.mtipoCreadoEl = mtipoCreadoEl;
	}

}
