package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PymeSocios generated by hbm2java
 */
@Entity
@Table(name = "PYME_SOCIOS", uniqueConstraints = @UniqueConstraint(columnNames = "SOC_EXTERNO"))
public class PymeSocios implements java.io.Serializable {

	private BigDecimal socId;
	private String socExterno;
	private String socNombre;
	private String socApellido1;
	private String socApellido2;
	private String socDireccion1;
	private String socDireccion2;
	private long socTipoCredito;
	private Long socGrupoClientes;
	private Long socTipoPlazo;
	private long socTipoSocio;
	private String socCreadoPor;
	private Date socCreadoEl;
	private Set<PymeNdEncCli> pymeNdEncClis = new HashSet<PymeNdEncCli>(0);
	private Set<PymeFacncEncProv> pymeFacncEncProvs = new HashSet<PymeFacncEncProv>(0);

	public PymeSocios() {
	}

	public PymeSocios(BigDecimal socId, String socExterno, String socNombre, String socApellido1, long socTipoCredito,
			long socTipoSocio) {
		this.socId = socId;
		this.socExterno = socExterno;
		this.socNombre = socNombre;
		this.socApellido1 = socApellido1;
		this.socTipoCredito = socTipoCredito;
		this.socTipoSocio = socTipoSocio;
	}

	public PymeSocios(BigDecimal socId, String socExterno, String socNombre, String socApellido1, String socApellido2,
			String socDireccion1, String socDireccion2, long socTipoCredito, Long socGrupoClientes, Long socTipoPlazo,
			long socTipoSocio, String socCreadoPor, Date socCreadoEl, Set<PymeNdEncCli> pymeNdEncClis,
			Set<PymeFacncEncProv> pymeFacncEncProvs) {
		this.socId = socId;
		this.socExterno = socExterno;
		this.socNombre = socNombre;
		this.socApellido1 = socApellido1;
		this.socApellido2 = socApellido2;
		this.socDireccion1 = socDireccion1;
		this.socDireccion2 = socDireccion2;
		this.socTipoCredito = socTipoCredito;
		this.socGrupoClientes = socGrupoClientes;
		this.socTipoPlazo = socTipoPlazo;
		this.socTipoSocio = socTipoSocio;
		this.socCreadoPor = socCreadoPor;
		this.socCreadoEl = socCreadoEl;
		this.pymeNdEncClis = pymeNdEncClis;
		this.pymeFacncEncProvs = pymeFacncEncProvs;
	}

	@Id

	@Column(name = "SOC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSocId() {
		return this.socId;
	}

	public void setSocId(BigDecimal socId) {
		this.socId = socId;
	}

	@Column(name = "SOC_EXTERNO", unique = true, nullable = false, length = 50)
	public String getSocExterno() {
		return this.socExterno;
	}

	public void setSocExterno(String socExterno) {
		this.socExterno = socExterno;
	}

	@Column(name = "SOC_NOMBRE", nullable = false, length = 100)
	public String getSocNombre() {
		return this.socNombre;
	}

	public void setSocNombre(String socNombre) {
		this.socNombre = socNombre;
	}

	@Column(name = "SOC_APELLIDO1", nullable = false, length = 100)
	public String getSocApellido1() {
		return this.socApellido1;
	}

	public void setSocApellido1(String socApellido1) {
		this.socApellido1 = socApellido1;
	}

	@Column(name = "SOC_APELLIDO2", length = 100)
	public String getSocApellido2() {
		return this.socApellido2;
	}

	public void setSocApellido2(String socApellido2) {
		this.socApellido2 = socApellido2;
	}

	@Column(name = "SOC_DIRECCION1", length = 500)
	public String getSocDireccion1() {
		return this.socDireccion1;
	}

	public void setSocDireccion1(String socDireccion1) {
		this.socDireccion1 = socDireccion1;
	}

	@Column(name = "SOC_DIRECCION2", length = 500)
	public String getSocDireccion2() {
		return this.socDireccion2;
	}

	public void setSocDireccion2(String socDireccion2) {
		this.socDireccion2 = socDireccion2;
	}

	@Column(name = "SOC_TIPO_CREDITO", nullable = false, precision = 10, scale = 0)
	public long getSocTipoCredito() {
		return this.socTipoCredito;
	}

	public void setSocTipoCredito(long socTipoCredito) {
		this.socTipoCredito = socTipoCredito;
	}

	@Column(name = "SOC_GRUPO_CLIENTES", precision = 10, scale = 0)
	public Long getSocGrupoClientes() {
		return this.socGrupoClientes;
	}

	public void setSocGrupoClientes(Long socGrupoClientes) {
		this.socGrupoClientes = socGrupoClientes;
	}

	@Column(name = "SOC_TIPO_PLAZO", precision = 10, scale = 0)
	public Long getSocTipoPlazo() {
		return this.socTipoPlazo;
	}

	public void setSocTipoPlazo(Long socTipoPlazo) {
		this.socTipoPlazo = socTipoPlazo;
	}

	@Column(name = "SOC_TIPO_SOCIO", nullable = false, precision = 10, scale = 0)
	public long getSocTipoSocio() {
		return this.socTipoSocio;
	}

	public void setSocTipoSocio(long socTipoSocio) {
		this.socTipoSocio = socTipoSocio;
	}

	@Column(name = "SOC_CREADO_POR", length = 20)
	public String getSocCreadoPor() {
		return this.socCreadoPor;
	}

	public void setSocCreadoPor(String socCreadoPor) {
		this.socCreadoPor = socCreadoPor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SOC_CREADO_EL", length = 7)
	public Date getSocCreadoEl() {
		return this.socCreadoEl;
	}

	public void setSocCreadoEl(Date socCreadoEl) {
		this.socCreadoEl = socCreadoEl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeSocios")
	public Set<PymeNdEncCli> getPymeNdEncClis() {
		return this.pymeNdEncClis;
	}

	public void setPymeNdEncClis(Set<PymeNdEncCli> pymeNdEncClis) {
		this.pymeNdEncClis = pymeNdEncClis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeSocios")
	public Set<PymeFacncEncProv> getPymeFacncEncProvs() {
		return this.pymeFacncEncProvs;
	}

	public void setPymeFacncEncProvs(Set<PymeFacncEncProv> pymeFacncEncProvs) {
		this.pymeFacncEncProvs = pymeFacncEncProvs;
	}

}
