package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeDtipos generated by hbm2java
 */
public class PymeDtipos implements java.io.Serializable {

	private long dtipoId;
	private PymeMtipos pymeMtipos;
	private String dtipoNombre;
	private boolean dtipoEstado;
	private Date dtipoCreadoEl;
	private BigDecimal dtipoCantidad;
	private Set<PymeProductos> pymeProductosesForProducTipo = new HashSet<PymeProductos>(0);
	private Set<PymeMlistaPrecios> pymeMlistaPrecioses = new HashSet<PymeMlistaPrecios>(0);
	private Set<PymeNdEncCli> pymeNdEncClisForNdcliEstado = new HashSet<PymeNdEncCli>(0);
	private Set<PymeEmpresa> pymeEmpresas = new HashSet<PymeEmpresa>(0);
	private Set<PymeNdEncCli> pymeNdEncClisForNdcliTipoFacnd = new HashSet<PymeNdEncCli>(0);
	private Set<PymeProductos> pymeProductosesForProducEstado = new HashSet<PymeProductos>(0);
	private Set<PymeProductos> pymeProductosesForProducMedida = new HashSet<PymeProductos>(0);
	private Set<PymeProyecto> pymeProyectos = new HashSet<PymeProyecto>(0);
	private Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovTipoDoc = new HashSet<PymeFacncEncProv>(0);
	private Set<PymeFacncEncCli> pymeFacncEncClisForFacTipoFacnd = new HashSet<PymeFacncEncCli>(0);
	private Set<PymeEtapa> pymeEtapas = new HashSet<PymeEtapa>(0);
	private Set<PymeFacncEncCli> pymeFacncEncClisForFacEstado = new HashSet<PymeFacncEncCli>(0);
	private Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovEstado = new HashSet<PymeFacncEncProv>(0);
	private Set<PymeFacncEncCli> pymeFacncEncClisForFacTipoDoc = new HashSet<PymeFacncEncCli>(0);
	private Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovTipoFacnd = new HashSet<PymeFacncEncProv>(0);
	private Set<PymeDsalidas> pymeDsalidasesForDsalTipoMov = new HashSet<PymeDsalidas>(0);
	private Set<PymeDsalidas> pymeDsalidasesForDsalEstadoDoc = new HashSet<PymeDsalidas>(0);
	private Set<PymeSocios> pymeSociosesForSocTipoSocio = new HashSet<PymeSocios>(0);
	private Set<PymeSocios> pymeSociosesForSocTipoCredito = new HashSet<PymeSocios>(0);
	private Set<PymeSocios> pymeSociosesForSocTipoPlazo = new HashSet<PymeSocios>(0);
	private Set<PymeSocios> pymeSociosesForSocGrupoClientes = new HashSet<PymeSocios>(0);
	private Set<PymeNdEncProv> pymeNdEncProvsForNdprovTipoFacnd = new HashSet<PymeNdEncProv>(0);
	private Set<PymeNdEncProv> pymeNdEncProvsForNdprovEstado = new HashSet<PymeNdEncProv>(0);
	private Set<PymeSubetapa> pymeSubetapas = new HashSet<PymeSubetapa>(0);

	public PymeDtipos() {
	}

	public PymeDtipos(long dtipoId, PymeMtipos pymeMtipos, String dtipoNombre, boolean dtipoEstado,
			Date dtipoCreadoEl) {
		this.dtipoId = dtipoId;
		this.pymeMtipos = pymeMtipos;
		this.dtipoNombre = dtipoNombre;
		this.dtipoEstado = dtipoEstado;
		this.dtipoCreadoEl = dtipoCreadoEl;
	}

	public PymeDtipos(long dtipoId, PymeMtipos pymeMtipos, String dtipoNombre, boolean dtipoEstado, Date dtipoCreadoEl,
			BigDecimal dtipoCantidad, Set<PymeProductos> pymeProductosesForProducTipo,
			Set<PymeMlistaPrecios> pymeMlistaPrecioses, Set<PymeNdEncCli> pymeNdEncClisForNdcliEstado,
			Set<PymeEmpresa> pymeEmpresas, Set<PymeNdEncCli> pymeNdEncClisForNdcliTipoFacnd,
			Set<PymeProductos> pymeProductosesForProducEstado, Set<PymeProductos> pymeProductosesForProducMedida,
			Set<PymeProyecto> pymeProyectos, Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovTipoDoc,
			Set<PymeFacncEncCli> pymeFacncEncClisForFacTipoFacnd, Set<PymeEtapa> pymeEtapas,
			Set<PymeFacncEncCli> pymeFacncEncClisForFacEstado, Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovEstado,
			Set<PymeFacncEncCli> pymeFacncEncClisForFacTipoDoc,
			Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovTipoFacnd, Set<PymeDsalidas> pymeDsalidasesForDsalTipoMov,
			Set<PymeDsalidas> pymeDsalidasesForDsalEstadoDoc, Set<PymeSocios> pymeSociosesForSocTipoSocio,
			Set<PymeSocios> pymeSociosesForSocTipoCredito, Set<PymeSocios> pymeSociosesForSocTipoPlazo,
			Set<PymeSocios> pymeSociosesForSocGrupoClientes, Set<PymeNdEncProv> pymeNdEncProvsForNdprovTipoFacnd,
			Set<PymeNdEncProv> pymeNdEncProvsForNdprovEstado, Set<PymeSubetapa> pymeSubetapas) {
		this.dtipoId = dtipoId;
		this.pymeMtipos = pymeMtipos;
		this.dtipoNombre = dtipoNombre;
		this.dtipoEstado = dtipoEstado;
		this.dtipoCreadoEl = dtipoCreadoEl;
		this.dtipoCantidad = dtipoCantidad;
		this.pymeProductosesForProducTipo = pymeProductosesForProducTipo;
		this.pymeMlistaPrecioses = pymeMlistaPrecioses;
		this.pymeNdEncClisForNdcliEstado = pymeNdEncClisForNdcliEstado;
		this.pymeEmpresas = pymeEmpresas;
		this.pymeNdEncClisForNdcliTipoFacnd = pymeNdEncClisForNdcliTipoFacnd;
		this.pymeProductosesForProducEstado = pymeProductosesForProducEstado;
		this.pymeProductosesForProducMedida = pymeProductosesForProducMedida;
		this.pymeProyectos = pymeProyectos;
		this.pymeFacncEncProvsForFacprovTipoDoc = pymeFacncEncProvsForFacprovTipoDoc;
		this.pymeFacncEncClisForFacTipoFacnd = pymeFacncEncClisForFacTipoFacnd;
		this.pymeEtapas = pymeEtapas;
		this.pymeFacncEncClisForFacEstado = pymeFacncEncClisForFacEstado;
		this.pymeFacncEncProvsForFacprovEstado = pymeFacncEncProvsForFacprovEstado;
		this.pymeFacncEncClisForFacTipoDoc = pymeFacncEncClisForFacTipoDoc;
		this.pymeFacncEncProvsForFacprovTipoFacnd = pymeFacncEncProvsForFacprovTipoFacnd;
		this.pymeDsalidasesForDsalTipoMov = pymeDsalidasesForDsalTipoMov;
		this.pymeDsalidasesForDsalEstadoDoc = pymeDsalidasesForDsalEstadoDoc;
		this.pymeSociosesForSocTipoSocio = pymeSociosesForSocTipoSocio;
		this.pymeSociosesForSocTipoCredito = pymeSociosesForSocTipoCredito;
		this.pymeSociosesForSocTipoPlazo = pymeSociosesForSocTipoPlazo;
		this.pymeSociosesForSocGrupoClientes = pymeSociosesForSocGrupoClientes;
		this.pymeNdEncProvsForNdprovTipoFacnd = pymeNdEncProvsForNdprovTipoFacnd;
		this.pymeNdEncProvsForNdprovEstado = pymeNdEncProvsForNdprovEstado;
		this.pymeSubetapas = pymeSubetapas;
	}

	public long getDtipoId() {
		return this.dtipoId;
	}

	public void setDtipoId(long dtipoId) {
		this.dtipoId = dtipoId;
	}

	public PymeMtipos getPymeMtipos() {
		return this.pymeMtipos;
	}

	public void setPymeMtipos(PymeMtipos pymeMtipos) {
		this.pymeMtipos = pymeMtipos;
	}

	public String getDtipoNombre() {
		return this.dtipoNombre;
	}

	public void setDtipoNombre(String dtipoNombre) {
		this.dtipoNombre = dtipoNombre;
	}

	public boolean isDtipoEstado() {
		return this.dtipoEstado;
	}

	public void setDtipoEstado(boolean dtipoEstado) {
		this.dtipoEstado = dtipoEstado;
	}

	public Date getDtipoCreadoEl() {
		return this.dtipoCreadoEl;
	}

	public void setDtipoCreadoEl(Date dtipoCreadoEl) {
		this.dtipoCreadoEl = dtipoCreadoEl;
	}

	public BigDecimal getDtipoCantidad() {
		return this.dtipoCantidad;
	}

	public void setDtipoCantidad(BigDecimal dtipoCantidad) {
		this.dtipoCantidad = dtipoCantidad;
	}

	public Set<PymeProductos> getPymeProductosesForProducTipo() {
		return this.pymeProductosesForProducTipo;
	}

	public void setPymeProductosesForProducTipo(Set<PymeProductos> pymeProductosesForProducTipo) {
		this.pymeProductosesForProducTipo = pymeProductosesForProducTipo;
	}

	public Set<PymeMlistaPrecios> getPymeMlistaPrecioses() {
		return this.pymeMlistaPrecioses;
	}

	public void setPymeMlistaPrecioses(Set<PymeMlistaPrecios> pymeMlistaPrecioses) {
		this.pymeMlistaPrecioses = pymeMlistaPrecioses;
	}

	public Set<PymeNdEncCli> getPymeNdEncClisForNdcliEstado() {
		return this.pymeNdEncClisForNdcliEstado;
	}

	public void setPymeNdEncClisForNdcliEstado(Set<PymeNdEncCli> pymeNdEncClisForNdcliEstado) {
		this.pymeNdEncClisForNdcliEstado = pymeNdEncClisForNdcliEstado;
	}

	public Set<PymeEmpresa> getPymeEmpresas() {
		return this.pymeEmpresas;
	}

	public void setPymeEmpresas(Set<PymeEmpresa> pymeEmpresas) {
		this.pymeEmpresas = pymeEmpresas;
	}

	public Set<PymeNdEncCli> getPymeNdEncClisForNdcliTipoFacnd() {
		return this.pymeNdEncClisForNdcliTipoFacnd;
	}

	public void setPymeNdEncClisForNdcliTipoFacnd(Set<PymeNdEncCli> pymeNdEncClisForNdcliTipoFacnd) {
		this.pymeNdEncClisForNdcliTipoFacnd = pymeNdEncClisForNdcliTipoFacnd;
	}

	public Set<PymeProductos> getPymeProductosesForProducEstado() {
		return this.pymeProductosesForProducEstado;
	}

	public void setPymeProductosesForProducEstado(Set<PymeProductos> pymeProductosesForProducEstado) {
		this.pymeProductosesForProducEstado = pymeProductosesForProducEstado;
	}

	public Set<PymeProductos> getPymeProductosesForProducMedida() {
		return this.pymeProductosesForProducMedida;
	}

	public void setPymeProductosesForProducMedida(Set<PymeProductos> pymeProductosesForProducMedida) {
		this.pymeProductosesForProducMedida = pymeProductosesForProducMedida;
	}

	public Set<PymeProyecto> getPymeProyectos() {
		return this.pymeProyectos;
	}

	public void setPymeProyectos(Set<PymeProyecto> pymeProyectos) {
		this.pymeProyectos = pymeProyectos;
	}

	public Set<PymeFacncEncProv> getPymeFacncEncProvsForFacprovTipoDoc() {
		return this.pymeFacncEncProvsForFacprovTipoDoc;
	}

	public void setPymeFacncEncProvsForFacprovTipoDoc(Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovTipoDoc) {
		this.pymeFacncEncProvsForFacprovTipoDoc = pymeFacncEncProvsForFacprovTipoDoc;
	}

	public Set<PymeFacncEncCli> getPymeFacncEncClisForFacTipoFacnd() {
		return this.pymeFacncEncClisForFacTipoFacnd;
	}

	public void setPymeFacncEncClisForFacTipoFacnd(Set<PymeFacncEncCli> pymeFacncEncClisForFacTipoFacnd) {
		this.pymeFacncEncClisForFacTipoFacnd = pymeFacncEncClisForFacTipoFacnd;
	}

	public Set<PymeEtapa> getPymeEtapas() {
		return this.pymeEtapas;
	}

	public void setPymeEtapas(Set<PymeEtapa> pymeEtapas) {
		this.pymeEtapas = pymeEtapas;
	}

	public Set<PymeFacncEncCli> getPymeFacncEncClisForFacEstado() {
		return this.pymeFacncEncClisForFacEstado;
	}

	public void setPymeFacncEncClisForFacEstado(Set<PymeFacncEncCli> pymeFacncEncClisForFacEstado) {
		this.pymeFacncEncClisForFacEstado = pymeFacncEncClisForFacEstado;
	}

	public Set<PymeFacncEncProv> getPymeFacncEncProvsForFacprovEstado() {
		return this.pymeFacncEncProvsForFacprovEstado;
	}

	public void setPymeFacncEncProvsForFacprovEstado(Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovEstado) {
		this.pymeFacncEncProvsForFacprovEstado = pymeFacncEncProvsForFacprovEstado;
	}

	public Set<PymeFacncEncCli> getPymeFacncEncClisForFacTipoDoc() {
		return this.pymeFacncEncClisForFacTipoDoc;
	}

	public void setPymeFacncEncClisForFacTipoDoc(Set<PymeFacncEncCli> pymeFacncEncClisForFacTipoDoc) {
		this.pymeFacncEncClisForFacTipoDoc = pymeFacncEncClisForFacTipoDoc;
	}

	public Set<PymeFacncEncProv> getPymeFacncEncProvsForFacprovTipoFacnd() {
		return this.pymeFacncEncProvsForFacprovTipoFacnd;
	}

	public void setPymeFacncEncProvsForFacprovTipoFacnd(Set<PymeFacncEncProv> pymeFacncEncProvsForFacprovTipoFacnd) {
		this.pymeFacncEncProvsForFacprovTipoFacnd = pymeFacncEncProvsForFacprovTipoFacnd;
	}

	public Set<PymeDsalidas> getPymeDsalidasesForDsalTipoMov() {
		return this.pymeDsalidasesForDsalTipoMov;
	}

	public void setPymeDsalidasesForDsalTipoMov(Set<PymeDsalidas> pymeDsalidasesForDsalTipoMov) {
		this.pymeDsalidasesForDsalTipoMov = pymeDsalidasesForDsalTipoMov;
	}

	public Set<PymeDsalidas> getPymeDsalidasesForDsalEstadoDoc() {
		return this.pymeDsalidasesForDsalEstadoDoc;
	}

	public void setPymeDsalidasesForDsalEstadoDoc(Set<PymeDsalidas> pymeDsalidasesForDsalEstadoDoc) {
		this.pymeDsalidasesForDsalEstadoDoc = pymeDsalidasesForDsalEstadoDoc;
	}

	public Set<PymeSocios> getPymeSociosesForSocTipoSocio() {
		return this.pymeSociosesForSocTipoSocio;
	}

	public void setPymeSociosesForSocTipoSocio(Set<PymeSocios> pymeSociosesForSocTipoSocio) {
		this.pymeSociosesForSocTipoSocio = pymeSociosesForSocTipoSocio;
	}

	public Set<PymeSocios> getPymeSociosesForSocTipoCredito() {
		return this.pymeSociosesForSocTipoCredito;
	}

	public void setPymeSociosesForSocTipoCredito(Set<PymeSocios> pymeSociosesForSocTipoCredito) {
		this.pymeSociosesForSocTipoCredito = pymeSociosesForSocTipoCredito;
	}

	public Set<PymeSocios> getPymeSociosesForSocTipoPlazo() {
		return this.pymeSociosesForSocTipoPlazo;
	}

	public void setPymeSociosesForSocTipoPlazo(Set<PymeSocios> pymeSociosesForSocTipoPlazo) {
		this.pymeSociosesForSocTipoPlazo = pymeSociosesForSocTipoPlazo;
	}

	public Set<PymeSocios> getPymeSociosesForSocGrupoClientes() {
		return this.pymeSociosesForSocGrupoClientes;
	}

	public void setPymeSociosesForSocGrupoClientes(Set<PymeSocios> pymeSociosesForSocGrupoClientes) {
		this.pymeSociosesForSocGrupoClientes = pymeSociosesForSocGrupoClientes;
	}

	public Set<PymeNdEncProv> getPymeNdEncProvsForNdprovTipoFacnd() {
		return this.pymeNdEncProvsForNdprovTipoFacnd;
	}

	public void setPymeNdEncProvsForNdprovTipoFacnd(Set<PymeNdEncProv> pymeNdEncProvsForNdprovTipoFacnd) {
		this.pymeNdEncProvsForNdprovTipoFacnd = pymeNdEncProvsForNdprovTipoFacnd;
	}

	public Set<PymeNdEncProv> getPymeNdEncProvsForNdprovEstado() {
		return this.pymeNdEncProvsForNdprovEstado;
	}

	public void setPymeNdEncProvsForNdprovEstado(Set<PymeNdEncProv> pymeNdEncProvsForNdprovEstado) {
		this.pymeNdEncProvsForNdprovEstado = pymeNdEncProvsForNdprovEstado;
	}

	public Set<PymeSubetapa> getPymeSubetapas() {
		return this.pymeSubetapas;
	}

	public void setPymeSubetapas(Set<PymeSubetapa> pymeSubetapas) {
		this.pymeSubetapas = pymeSubetapas;
	}

}
