package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * PymeSysUsers generated by hbm2java
 */
public class PymeSysUsers implements java.io.Serializable {

	private long suId;
	private PymeEmpresa pymeEmpresa;
	private String suIdentificacion;
	private String suPassword;
	private String suNombre;
	private String suApellido1;
	private String suApellido2;
	private String suEmail;
	private String suTelefono;
	private String suSexo;
	private Date suCreadoEl;
	private String suCreadoPor;
	private String suCodigo;

	public PymeSysUsers() {
	}

	public PymeSysUsers(long suId, PymeEmpresa pymeEmpresa, String suPassword, String suNombre, String suApellido1,
			String suCodigo) {
		this.suId = suId;
		this.pymeEmpresa = pymeEmpresa;
		this.suPassword = suPassword;
		this.suNombre = suNombre;
		this.suApellido1 = suApellido1;
		this.suCodigo = suCodigo;
	}

	public PymeSysUsers(long suId, PymeEmpresa pymeEmpresa, String suIdentificacion, String suPassword, String suNombre,
			String suApellido1, String suApellido2, String suEmail, String suTelefono, String suSexo, Date suCreadoEl,
			String suCreadoPor, String suCodigo) {
		this.suId = suId;
		this.pymeEmpresa = pymeEmpresa;
		this.suIdentificacion = suIdentificacion;
		this.suPassword = suPassword;
		this.suNombre = suNombre;
		this.suApellido1 = suApellido1;
		this.suApellido2 = suApellido2;
		this.suEmail = suEmail;
		this.suTelefono = suTelefono;
		this.suSexo = suSexo;
		this.suCreadoEl = suCreadoEl;
		this.suCreadoPor = suCreadoPor;
		this.suCodigo = suCodigo;
	}

	public long getSuId() {
		return this.suId;
	}

	public void setSuId(long suId) {
		this.suId = suId;
	}

	public PymeEmpresa getPymeEmpresa() {
		return this.pymeEmpresa;
	}

	public void setPymeEmpresa(PymeEmpresa pymeEmpresa) {
		this.pymeEmpresa = pymeEmpresa;
	}

	public String getSuIdentificacion() {
		return this.suIdentificacion;
	}

	public void setSuIdentificacion(String suIdentificacion) {
		this.suIdentificacion = suIdentificacion;
	}

	public String getSuPassword() {
		return this.suPassword;
	}

	public void setSuPassword(String suPassword) {
		this.suPassword = suPassword;
	}

	public String getSuNombre() {
		return this.suNombre;
	}

	public void setSuNombre(String suNombre) {
		this.suNombre = suNombre;
	}

	public String getSuApellido1() {
		return this.suApellido1;
	}

	public void setSuApellido1(String suApellido1) {
		this.suApellido1 = suApellido1;
	}

	public String getSuApellido2() {
		return this.suApellido2;
	}

	public void setSuApellido2(String suApellido2) {
		this.suApellido2 = suApellido2;
	}

	public String getSuEmail() {
		return this.suEmail;
	}

	public void setSuEmail(String suEmail) {
		this.suEmail = suEmail;
	}

	public String getSuTelefono() {
		return this.suTelefono;
	}

	public void setSuTelefono(String suTelefono) {
		this.suTelefono = suTelefono;
	}

	public String getSuSexo() {
		return this.suSexo;
	}

	public void setSuSexo(String suSexo) {
		this.suSexo = suSexo;
	}

	public Date getSuCreadoEl() {
		return this.suCreadoEl;
	}

	public void setSuCreadoEl(Date suCreadoEl) {
		this.suCreadoEl = suCreadoEl;
	}

	public String getSuCreadoPor() {
		return this.suCreadoPor;
	}

	public void setSuCreadoPor(String suCreadoPor) {
		this.suCreadoPor = suCreadoPor;
	}

	public String getSuCodigo() {
		return this.suCodigo;
	}

	public void setSuCodigo(String suCodigo) {
		this.suCodigo = suCodigo;
	}

}
