package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeEtapa generated by hbm2java
 */
@Entity
@Table(name = "PYME_ETAPA")
public class PymeEtapa implements java.io.Serializable {

	private long etaId;
	private PymeProyecto pymeProyecto;
	private String etaNombre;
	private String etaDescripcion;
	private Long etaEstado;
	private Date creadoEl;
	private String creadoPor;
	private Set<PymeSubetapa> pymeSubetapas = new HashSet<PymeSubetapa>(0);

	public PymeEtapa() {
	}

	public PymeEtapa(long etaId, PymeProyecto pymeProyecto, String etaNombre) {
		this.etaId = etaId;
		this.pymeProyecto = pymeProyecto;
		this.etaNombre = etaNombre;
	}

	public PymeEtapa(long etaId, PymeProyecto pymeProyecto, String etaNombre, String etaDescripcion, Long etaEstado,
			Date creadoEl, String creadoPor, Set<PymeSubetapa> pymeSubetapas) {
		this.etaId = etaId;
		this.pymeProyecto = pymeProyecto;
		this.etaNombre = etaNombre;
		this.etaDescripcion = etaDescripcion;
		this.etaEstado = etaEstado;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.pymeSubetapas = pymeSubetapas;
	}

	@Id

	@Column(name = "ETA_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getEtaId() {
		return this.etaId;
	}

	public void setEtaId(long etaId) {
		this.etaId = etaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROY_ID", nullable = false)
	public PymeProyecto getPymeProyecto() {
		return this.pymeProyecto;
	}

	public void setPymeProyecto(PymeProyecto pymeProyecto) {
		this.pymeProyecto = pymeProyecto;
	}

	@Column(name = "ETA_NOMBRE", nullable = false, length = 100)
	public String getEtaNombre() {
		return this.etaNombre;
	}

	public void setEtaNombre(String etaNombre) {
		this.etaNombre = etaNombre;
	}

	@Column(name = "ETA_DESCRIPCION", length = 500)
	public String getEtaDescripcion() {
		return this.etaDescripcion;
	}

	public void setEtaDescripcion(String etaDescripcion) {
		this.etaDescripcion = etaDescripcion;
	}

	@Column(name = "ETA_ESTADO", precision = 10, scale = 0)
	public Long getEtaEstado() {
		return this.etaEstado;
	}

	public void setEtaEstado(Long etaEstado) {
		this.etaEstado = etaEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREADO_EL", length = 7)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Column(name = "CREADO_POR", length = 200)
	public String getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeEtapa")
	public Set<PymeSubetapa> getPymeSubetapas() {
		return this.pymeSubetapas;
	}

	public void setPymeSubetapas(Set<PymeSubetapa> pymeSubetapas) {
		this.pymeSubetapas = pymeSubetapas;
	}

}
