package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * PymeDsalidas generated by hbm2java
 */
public class PymeDsalidas implements java.io.Serializable {

	private long dsalId;
	private PymeProductos pymeProductos;
	private PymeDtipos pymeDtiposByDsalTipoMov;
	private PymeMsalidas pymeMsalidas;
	private PymeDtipos pymeDtiposByDsalEstadoDoc;
	private long dsalCantidad;
	private Date dsalFechaSalida;
	private String dsalCreadoPor;
	private String dsalAutorizadoPor;

	public PymeDsalidas() {
	}

	public PymeDsalidas(long dsalId, PymeProductos pymeProductos, PymeDtipos pymeDtiposByDsalTipoMov,
			PymeMsalidas pymeMsalidas, long dsalCantidad) {
		this.dsalId = dsalId;
		this.pymeProductos = pymeProductos;
		this.pymeDtiposByDsalTipoMov = pymeDtiposByDsalTipoMov;
		this.pymeMsalidas = pymeMsalidas;
		this.dsalCantidad = dsalCantidad;
	}

	public PymeDsalidas(long dsalId, PymeProductos pymeProductos, PymeDtipos pymeDtiposByDsalTipoMov,
			PymeMsalidas pymeMsalidas, PymeDtipos pymeDtiposByDsalEstadoDoc, long dsalCantidad, Date dsalFechaSalida,
			String dsalCreadoPor, String dsalAutorizadoPor) {
		this.dsalId = dsalId;
		this.pymeProductos = pymeProductos;
		this.pymeDtiposByDsalTipoMov = pymeDtiposByDsalTipoMov;
		this.pymeMsalidas = pymeMsalidas;
		this.pymeDtiposByDsalEstadoDoc = pymeDtiposByDsalEstadoDoc;
		this.dsalCantidad = dsalCantidad;
		this.dsalFechaSalida = dsalFechaSalida;
		this.dsalCreadoPor = dsalCreadoPor;
		this.dsalAutorizadoPor = dsalAutorizadoPor;
	}

	public long getDsalId() {
		return this.dsalId;
	}

	public void setDsalId(long dsalId) {
		this.dsalId = dsalId;
	}

	public PymeProductos getPymeProductos() {
		return this.pymeProductos;
	}

	public void setPymeProductos(PymeProductos pymeProductos) {
		this.pymeProductos = pymeProductos;
	}

	public PymeDtipos getPymeDtiposByDsalTipoMov() {
		return this.pymeDtiposByDsalTipoMov;
	}

	public void setPymeDtiposByDsalTipoMov(PymeDtipos pymeDtiposByDsalTipoMov) {
		this.pymeDtiposByDsalTipoMov = pymeDtiposByDsalTipoMov;
	}

	public PymeMsalidas getPymeMsalidas() {
		return this.pymeMsalidas;
	}

	public void setPymeMsalidas(PymeMsalidas pymeMsalidas) {
		this.pymeMsalidas = pymeMsalidas;
	}

	public PymeDtipos getPymeDtiposByDsalEstadoDoc() {
		return this.pymeDtiposByDsalEstadoDoc;
	}

	public void setPymeDtiposByDsalEstadoDoc(PymeDtipos pymeDtiposByDsalEstadoDoc) {
		this.pymeDtiposByDsalEstadoDoc = pymeDtiposByDsalEstadoDoc;
	}

	public long getDsalCantidad() {
		return this.dsalCantidad;
	}

	public void setDsalCantidad(long dsalCantidad) {
		this.dsalCantidad = dsalCantidad;
	}

	public Date getDsalFechaSalida() {
		return this.dsalFechaSalida;
	}

	public void setDsalFechaSalida(Date dsalFechaSalida) {
		this.dsalFechaSalida = dsalFechaSalida;
	}

	public String getDsalCreadoPor() {
		return this.dsalCreadoPor;
	}

	public void setDsalCreadoPor(String dsalCreadoPor) {
		this.dsalCreadoPor = dsalCreadoPor;
	}

	public String getDsalAutorizadoPor() {
		return this.dsalAutorizadoPor;
	}

	public void setDsalAutorizadoPor(String dsalAutorizadoPor) {
		this.dsalAutorizadoPor = dsalAutorizadoPor;
	}

}
