package com.gotn.model;
// Generated Jul 30, 2016 2:59:38 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeFacncEncProv generated by hbm2java
 */
@Entity
@Table(name = "PYME_FACNC_ENC_PROV")
public class PymeFacncEncProv implements java.io.Serializable {

	private long facprovId;
	private PymeSocios pymeSocios;
	private long facprovConsectivo;
	private String facprovSocNombre;
	private BigDecimal facprovTotalLocal;
	private BigDecimal facprovTotalExtranjero;
	private String facprovTipoCambio;
	private Date facprovFechaDoc;
	private Date facprovContabilizacion;
	private Long facprovDocBase;
	private Long facprovDocDestino;
	private long facprovTipoDoc;
	private BigDecimal facprovEstado;
	private String facprovComentarios;
	private BigDecimal proyId;
	private long facprovTipoFacnd;
	private Set<PymeFacncDetProv> pymeFacncDetProvs = new HashSet<PymeFacncDetProv>(0);

	public PymeFacncEncProv() {
	}

	public PymeFacncEncProv(long facprovId, long facprovConsectivo, long facprovTipoDoc, BigDecimal facprovEstado,
			BigDecimal proyId, long facprovTipoFacnd) {
		this.facprovId = facprovId;
		this.facprovConsectivo = facprovConsectivo;
		this.facprovTipoDoc = facprovTipoDoc;
		this.facprovEstado = facprovEstado;
		this.proyId = proyId;
		this.facprovTipoFacnd = facprovTipoFacnd;
	}

	public PymeFacncEncProv(long facprovId, PymeSocios pymeSocios, long facprovConsectivo, String facprovSocNombre,
			BigDecimal facprovTotalLocal, BigDecimal facprovTotalExtranjero, String facprovTipoCambio,
			Date facprovFechaDoc, Date facprovContabilizacion, Long facprovDocBase, Long facprovDocDestino,
			long facprovTipoDoc, BigDecimal facprovEstado, String facprovComentarios, BigDecimal proyId,
			long facprovTipoFacnd, Set<PymeFacncDetProv> pymeFacncDetProvs) {
		this.facprovId = facprovId;
		this.pymeSocios = pymeSocios;
		this.facprovConsectivo = facprovConsectivo;
		this.facprovSocNombre = facprovSocNombre;
		this.facprovTotalLocal = facprovTotalLocal;
		this.facprovTotalExtranjero = facprovTotalExtranjero;
		this.facprovTipoCambio = facprovTipoCambio;
		this.facprovFechaDoc = facprovFechaDoc;
		this.facprovContabilizacion = facprovContabilizacion;
		this.facprovDocBase = facprovDocBase;
		this.facprovDocDestino = facprovDocDestino;
		this.facprovTipoDoc = facprovTipoDoc;
		this.facprovEstado = facprovEstado;
		this.facprovComentarios = facprovComentarios;
		this.proyId = proyId;
		this.facprovTipoFacnd = facprovTipoFacnd;
		this.pymeFacncDetProvs = pymeFacncDetProvs;
	}

	@Id

	@Column(name = "FACPROV_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public long getFacprovId() {
		return this.facprovId;
	}

	public void setFacprovId(long facprovId) {
		this.facprovId = facprovId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SOC")
	public PymeSocios getPymeSocios() {
		return this.pymeSocios;
	}

	public void setPymeSocios(PymeSocios pymeSocios) {
		this.pymeSocios = pymeSocios;
	}

	@Column(name = "FACPROV_CONSECTIVO", nullable = false, precision = 18, scale = 0)
	public long getFacprovConsectivo() {
		return this.facprovConsectivo;
	}

	public void setFacprovConsectivo(long facprovConsectivo) {
		this.facprovConsectivo = facprovConsectivo;
	}

	@Column(name = "FACPROV_SOC_NOMBRE", length = 200)
	public String getFacprovSocNombre() {
		return this.facprovSocNombre;
	}

	public void setFacprovSocNombre(String facprovSocNombre) {
		this.facprovSocNombre = facprovSocNombre;
	}

	@Column(name = "FACPROV_TOTAL_LOCAL", precision = 18, scale = 3)
	public BigDecimal getFacprovTotalLocal() {
		return this.facprovTotalLocal;
	}

	public void setFacprovTotalLocal(BigDecimal facprovTotalLocal) {
		this.facprovTotalLocal = facprovTotalLocal;
	}

	@Column(name = "FACPROV_TOTAL_EXTRANJERO", precision = 18, scale = 3)
	public BigDecimal getFacprovTotalExtranjero() {
		return this.facprovTotalExtranjero;
	}

	public void setFacprovTotalExtranjero(BigDecimal facprovTotalExtranjero) {
		this.facprovTotalExtranjero = facprovTotalExtranjero;
	}

	@Column(name = "FACPROV_TIPO_CAMBIO", length = 20)
	public String getFacprovTipoCambio() {
		return this.facprovTipoCambio;
	}

	public void setFacprovTipoCambio(String facprovTipoCambio) {
		this.facprovTipoCambio = facprovTipoCambio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FACPROV_FECHA_DOC", length = 7)
	public Date getFacprovFechaDoc() {
		return this.facprovFechaDoc;
	}

	public void setFacprovFechaDoc(Date facprovFechaDoc) {
		this.facprovFechaDoc = facprovFechaDoc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FACPROV_CONTABILIZACION", length = 7)
	public Date getFacprovContabilizacion() {
		return this.facprovContabilizacion;
	}

	public void setFacprovContabilizacion(Date facprovContabilizacion) {
		this.facprovContabilizacion = facprovContabilizacion;
	}

	@Column(name = "FACPROV_DOC_BASE", precision = 18, scale = 0)
	public Long getFacprovDocBase() {
		return this.facprovDocBase;
	}

	public void setFacprovDocBase(Long facprovDocBase) {
		this.facprovDocBase = facprovDocBase;
	}

	@Column(name = "FACPROV_DOC_DESTINO", precision = 18, scale = 0)
	public Long getFacprovDocDestino() {
		return this.facprovDocDestino;
	}

	public void setFacprovDocDestino(Long facprovDocDestino) {
		this.facprovDocDestino = facprovDocDestino;
	}

	@Column(name = "FACPROV_TIPO_DOC", nullable = false, precision = 10, scale = 0)
	public long getFacprovTipoDoc() {
		return this.facprovTipoDoc;
	}

	public void setFacprovTipoDoc(long facprovTipoDoc) {
		this.facprovTipoDoc = facprovTipoDoc;
	}

	@Column(name = "FACPROV_ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getFacprovEstado() {
		return this.facprovEstado;
	}

	public void setFacprovEstado(BigDecimal facprovEstado) {
		this.facprovEstado = facprovEstado;
	}

	@Column(name = "FACPROV_COMENTARIOS", length = 200)
	public String getFacprovComentarios() {
		return this.facprovComentarios;
	}

	public void setFacprovComentarios(String facprovComentarios) {
		this.facprovComentarios = facprovComentarios;
	}

	@Column(name = "PROY_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getProyId() {
		return this.proyId;
	}

	public void setProyId(BigDecimal proyId) {
		this.proyId = proyId;
	}

	@Column(name = "FACPROV_TIPO_FACND", nullable = false, precision = 10, scale = 0)
	public long getFacprovTipoFacnd() {
		return this.facprovTipoFacnd;
	}

	public void setFacprovTipoFacnd(long facprovTipoFacnd) {
		this.facprovTipoFacnd = facprovTipoFacnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeFacncEncProv")
	public Set<PymeFacncDetProv> getPymeFacncDetProvs() {
		return this.pymeFacncDetProvs;
	}

	public void setPymeFacncDetProvs(Set<PymeFacncDetProv> pymeFacncDetProvs) {
		this.pymeFacncDetProvs = pymeFacncDetProvs;
	}

}
