package com.gotn.model;
// Generated Jul 24, 2016 4:29:10 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PymeFacncEncProv generated by hbm2java
 */
public class PymeFacncEncProv implements java.io.Serializable {

	private long facprovId;
	private PymeDtipos pymeDtiposByFacprovTipoFacnd;
	private PymeDtipos pymeDtiposByFacprovEstado;
	private PymeDtipos pymeDtiposByFacprovTipoDoc;
	private long facprovConsectivo;
	private BigDecimal idSoc;
	private String facprovSocNombre;
	private BigDecimal facprovTotalLocal;
	private BigDecimal facprovTotalExtranjero;
	private String facprovTipoCambio;
	private Date facprovFechaDoc;
	private Date facprovContabilizacion;
	private Long facprovDocBase;
	private Long facprovDocDestino;
	private String facprovComentarios;
	private BigDecimal proyId;
	private Set<PymeFacncDetProv> pymeFacncDetProvs = new HashSet<PymeFacncDetProv>(0);

	public PymeFacncEncProv() {
	}

	public PymeFacncEncProv(long facprovId, PymeDtipos pymeDtiposByFacprovTipoFacnd,
			PymeDtipos pymeDtiposByFacprovEstado, PymeDtipos pymeDtiposByFacprovTipoDoc, long facprovConsectivo,
			BigDecimal proyId) {
		this.facprovId = facprovId;
		this.pymeDtiposByFacprovTipoFacnd = pymeDtiposByFacprovTipoFacnd;
		this.pymeDtiposByFacprovEstado = pymeDtiposByFacprovEstado;
		this.pymeDtiposByFacprovTipoDoc = pymeDtiposByFacprovTipoDoc;
		this.facprovConsectivo = facprovConsectivo;
		this.proyId = proyId;
	}

	public PymeFacncEncProv(long facprovId, PymeDtipos pymeDtiposByFacprovTipoFacnd,
			PymeDtipos pymeDtiposByFacprovEstado, PymeDtipos pymeDtiposByFacprovTipoDoc, long facprovConsectivo,
			BigDecimal idSoc, String facprovSocNombre, BigDecimal facprovTotalLocal, BigDecimal facprovTotalExtranjero,
			String facprovTipoCambio, Date facprovFechaDoc, Date facprovContabilizacion, Long facprovDocBase,
			Long facprovDocDestino, String facprovComentarios, BigDecimal proyId,
			Set<PymeFacncDetProv> pymeFacncDetProvs) {
		this.facprovId = facprovId;
		this.pymeDtiposByFacprovTipoFacnd = pymeDtiposByFacprovTipoFacnd;
		this.pymeDtiposByFacprovEstado = pymeDtiposByFacprovEstado;
		this.pymeDtiposByFacprovTipoDoc = pymeDtiposByFacprovTipoDoc;
		this.facprovConsectivo = facprovConsectivo;
		this.idSoc = idSoc;
		this.facprovSocNombre = facprovSocNombre;
		this.facprovTotalLocal = facprovTotalLocal;
		this.facprovTotalExtranjero = facprovTotalExtranjero;
		this.facprovTipoCambio = facprovTipoCambio;
		this.facprovFechaDoc = facprovFechaDoc;
		this.facprovContabilizacion = facprovContabilizacion;
		this.facprovDocBase = facprovDocBase;
		this.facprovDocDestino = facprovDocDestino;
		this.facprovComentarios = facprovComentarios;
		this.proyId = proyId;
		this.pymeFacncDetProvs = pymeFacncDetProvs;
	}

	public long getFacprovId() {
		return this.facprovId;
	}

	public void setFacprovId(long facprovId) {
		this.facprovId = facprovId;
	}

	public PymeDtipos getPymeDtiposByFacprovTipoFacnd() {
		return this.pymeDtiposByFacprovTipoFacnd;
	}

	public void setPymeDtiposByFacprovTipoFacnd(PymeDtipos pymeDtiposByFacprovTipoFacnd) {
		this.pymeDtiposByFacprovTipoFacnd = pymeDtiposByFacprovTipoFacnd;
	}

	public PymeDtipos getPymeDtiposByFacprovEstado() {
		return this.pymeDtiposByFacprovEstado;
	}

	public void setPymeDtiposByFacprovEstado(PymeDtipos pymeDtiposByFacprovEstado) {
		this.pymeDtiposByFacprovEstado = pymeDtiposByFacprovEstado;
	}

	public PymeDtipos getPymeDtiposByFacprovTipoDoc() {
		return this.pymeDtiposByFacprovTipoDoc;
	}

	public void setPymeDtiposByFacprovTipoDoc(PymeDtipos pymeDtiposByFacprovTipoDoc) {
		this.pymeDtiposByFacprovTipoDoc = pymeDtiposByFacprovTipoDoc;
	}

	public long getFacprovConsectivo() {
		return this.facprovConsectivo;
	}

	public void setFacprovConsectivo(long facprovConsectivo) {
		this.facprovConsectivo = facprovConsectivo;
	}

	public BigDecimal getIdSoc() {
		return this.idSoc;
	}

	public void setIdSoc(BigDecimal idSoc) {
		this.idSoc = idSoc;
	}

	public String getFacprovSocNombre() {
		return this.facprovSocNombre;
	}

	public void setFacprovSocNombre(String facprovSocNombre) {
		this.facprovSocNombre = facprovSocNombre;
	}

	public BigDecimal getFacprovTotalLocal() {
		return this.facprovTotalLocal;
	}

	public void setFacprovTotalLocal(BigDecimal facprovTotalLocal) {
		this.facprovTotalLocal = facprovTotalLocal;
	}

	public BigDecimal getFacprovTotalExtranjero() {
		return this.facprovTotalExtranjero;
	}

	public void setFacprovTotalExtranjero(BigDecimal facprovTotalExtranjero) {
		this.facprovTotalExtranjero = facprovTotalExtranjero;
	}

	public String getFacprovTipoCambio() {
		return this.facprovTipoCambio;
	}

	public void setFacprovTipoCambio(String facprovTipoCambio) {
		this.facprovTipoCambio = facprovTipoCambio;
	}

	public Date getFacprovFechaDoc() {
		return this.facprovFechaDoc;
	}

	public void setFacprovFechaDoc(Date facprovFechaDoc) {
		this.facprovFechaDoc = facprovFechaDoc;
	}

	public Date getFacprovContabilizacion() {
		return this.facprovContabilizacion;
	}

	public void setFacprovContabilizacion(Date facprovContabilizacion) {
		this.facprovContabilizacion = facprovContabilizacion;
	}

	public Long getFacprovDocBase() {
		return this.facprovDocBase;
	}

	public void setFacprovDocBase(Long facprovDocBase) {
		this.facprovDocBase = facprovDocBase;
	}

	public Long getFacprovDocDestino() {
		return this.facprovDocDestino;
	}

	public void setFacprovDocDestino(Long facprovDocDestino) {
		this.facprovDocDestino = facprovDocDestino;
	}

	public String getFacprovComentarios() {
		return this.facprovComentarios;
	}

	public void setFacprovComentarios(String facprovComentarios) {
		this.facprovComentarios = facprovComentarios;
	}

	public BigDecimal getProyId() {
		return this.proyId;
	}

	public void setProyId(BigDecimal proyId) {
		this.proyId = proyId;
	}

	public Set<PymeFacncDetProv> getPymeFacncDetProvs() {
		return this.pymeFacncDetProvs;
	}

	public void setPymeFacncDetProvs(Set<PymeFacncDetProv> pymeFacncDetProvs) {
		this.pymeFacncDetProvs = pymeFacncDetProvs;
	}

}
