package com.gotn.model;
// Generated Jul 27, 2016 9:16:01 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PymeProyecto generated by hbm2java
 */
@Entity
@Table(name = "PYME_PROYECTO")
public class PymeProyecto implements java.io.Serializable {

	private long proyId;
	private PymeEmpresa pymeEmpresa;
	private PymeDtipos pymeDtipos;
	private String proyNombre;
	private String proyDescripcion;
	private String proyCreadoPor;
	private Date proyCreadoEl;
	private Set<PymeSysSeguridad> pymeSysSeguridads = new HashSet<PymeSysSeguridad>(0);
	private Set<PymeFacncEncCli> pymeFacncEncClis = new HashSet<PymeFacncEncCli>(0);
	private Set<PymeEtapa> pymeEtapas = new HashSet<PymeEtapa>(0);

	public PymeProyecto() {
	}

	public PymeProyecto(long proyId, PymeEmpresa pymeEmpresa, PymeDtipos pymeDtipos, String proyNombre,
			String proyDescripcion, String proyCreadoPor, Date proyCreadoEl) {
		this.proyId = proyId;
		this.pymeEmpresa = pymeEmpresa;
		this.pymeDtipos = pymeDtipos;
		this.proyNombre = proyNombre;
		this.proyDescripcion = proyDescripcion;
		this.proyCreadoPor = proyCreadoPor;
		this.proyCreadoEl = proyCreadoEl;
	}

	public PymeProyecto(long proyId, PymeEmpresa pymeEmpresa, PymeDtipos pymeDtipos, String proyNombre,
			String proyDescripcion, String proyCreadoPor, Date proyCreadoEl, Set<PymeSysSeguridad> pymeSysSeguridads,
			Set<PymeFacncEncCli> pymeFacncEncClis, Set<PymeEtapa> pymeEtapas) {
		this.proyId = proyId;
		this.pymeEmpresa = pymeEmpresa;
		this.pymeDtipos = pymeDtipos;
		this.proyNombre = proyNombre;
		this.proyDescripcion = proyDescripcion;
		this.proyCreadoPor = proyCreadoPor;
		this.proyCreadoEl = proyCreadoEl;
		this.pymeSysSeguridads = pymeSysSeguridads;
		this.pymeFacncEncClis = pymeFacncEncClis;
		this.pymeEtapas = pymeEtapas;
	}

	@Id

	@Column(name = "PROY_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getProyId() {
		return this.proyId;
	}

	public void setProyId(long proyId) {
		this.proyId = proyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID", nullable = false)
	public PymeEmpresa getPymeEmpresa() {
		return this.pymeEmpresa;
	}

	public void setPymeEmpresa(PymeEmpresa pymeEmpresa) {
		this.pymeEmpresa = pymeEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROY_ESTADO", nullable = false)
	public PymeDtipos getPymeDtipos() {
		return this.pymeDtipos;
	}

	public void setPymeDtipos(PymeDtipos pymeDtipos) {
		this.pymeDtipos = pymeDtipos;
	}

	@Column(name = "PROY_NOMBRE", nullable = false, length = 200)
	public String getProyNombre() {
		return this.proyNombre;
	}

	public void setProyNombre(String proyNombre) {
		this.proyNombre = proyNombre;
	}

	@Column(name = "PROY_DESCRIPCION", nullable = false, length = 1000)
	public String getProyDescripcion() {
		return this.proyDescripcion;
	}

	public void setProyDescripcion(String proyDescripcion) {
		this.proyDescripcion = proyDescripcion;
	}

	@Column(name = "PROY_CREADO_POR", nullable = false, length = 100)
	public String getProyCreadoPor() {
		return this.proyCreadoPor;
	}

	public void setProyCreadoPor(String proyCreadoPor) {
		this.proyCreadoPor = proyCreadoPor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PROY_CREADO_EL", nullable = false, length = 7)
	public Date getProyCreadoEl() {
		return this.proyCreadoEl;
	}

	public void setProyCreadoEl(Date proyCreadoEl) {
		this.proyCreadoEl = proyCreadoEl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProyecto")
	public Set<PymeSysSeguridad> getPymeSysSeguridads() {
		return this.pymeSysSeguridads;
	}

	public void setPymeSysSeguridads(Set<PymeSysSeguridad> pymeSysSeguridads) {
		this.pymeSysSeguridads = pymeSysSeguridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProyecto")
	public Set<PymeFacncEncCli> getPymeFacncEncClis() {
		return this.pymeFacncEncClis;
	}

	public void setPymeFacncEncClis(Set<PymeFacncEncCli> pymeFacncEncClis) {
		this.pymeFacncEncClis = pymeFacncEncClis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pymeProyecto")
	public Set<PymeEtapa> getPymeEtapas() {
		return this.pymeEtapas;
	}

	public void setPymeEtapas(Set<PymeEtapa> pymeEtapas) {
		this.pymeEtapas = pymeEtapas;
	}

}
